--------------------------------------------------------
--  DDL for Table FIAS_HOUSE68
--------------------------------------------------------

  CREATE TABLE "FCR"."FIAS_HOUSE68" 
   (	"AOGUID" VARCHAR2(36 BYTE), 
	"BUILDNUM" VARCHAR2(10 BYTE), 
	"ENDDATE" DATE, 
	"ESTSTATUS" NUMBER, 
	"HOUSEGUID" VARCHAR2(36 BYTE), 
	"HOUSEID" VARCHAR2(36 BYTE), 
	"HOUSENUM" VARCHAR2(10 BYTE), 
	"STATSTATUS" NUMBER, 
	"IFNSFL" VARCHAR2(4 BYTE), 
	"IFNSUL" VARCHAR2(4 BYTE), 
	"OKATO" VARCHAR2(11 BYTE), 
	"OKTMO" VARCHAR2(11 BYTE), 
	"POSTALCODE" VARCHAR2(6 BYTE), 
	"STARTDATE" DATE, 
	"STRUCNUM" VARCHAR2(10 BYTE), 
	"STRSTATUS" NUMBER, 
	"TERRIFNSFL" VARCHAR2(4 BYTE), 
	"TERRIFNSUL" VARCHAR2(4 BYTE), 
	"UPDATEDATE" DATE, 
	"NORMDOC" VARCHAR2(36 BYTE), 
	"COUNTER" NUMBER, 
	"CADNUM" VARCHAR2(100 BYTE), 
	"DIVTYPE" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS#DATA1" ;
