--------------------------------------------------------
--  DDL for Table HOSTS
--------------------------------------------------------

  CREATE TABLE "FCR"."HOSTS" 
   (	"C#ID" VARCHAR2(20 BYTE), 
	"C#HOSTNAME" VARCHAR2(200 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 8192 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS#DATA1" ;
  GRANT FLASHBACK ON "FCR"."HOSTS" TO PUBLIC;
  GRANT DEBUG ON "FCR"."HOSTS" TO PUBLIC;
  GRANT QUERY REWRITE ON "FCR"."HOSTS" TO PUBLIC;
  GRANT ON COMMIT REFRESH ON "FCR"."HOSTS" TO PUBLIC;
  GRANT FLASHBACK ON "FCR"."HOSTS" TO "KAN";
  GRANT DEBUG ON "FCR"."HOSTS" TO "KAN";
  GRANT ALTER ON "FCR"."HOSTS" TO "KAN";
  GRANT QUERY REWRITE ON "FCR"."HOSTS" TO "KAN";
  GRANT ON COMMIT REFRESH ON "FCR"."HOSTS" TO "KAN";
  GRANT REFERENCES ON "FCR"."HOSTS" TO "KAN";
  GRANT UPDATE ON "FCR"."HOSTS" TO "KAN";
  GRANT SELECT ON "FCR"."HOSTS" TO "KAN";
  GRANT INSERT ON "FCR"."HOSTS" TO "KAN";
  GRANT INDEX ON "FCR"."HOSTS" TO "KAN";
  GRANT DELETE ON "FCR"."HOSTS" TO "KAN";
