--------------------------------------------------------
--  DDL for Index I#TEMP_PAY_STROITEL_LSO
--------------------------------------------------------

  CREATE INDEX "FCR"."I#TEMP_PAY_STROITEL_LSO" ON "FCR"."T#TEMP_PAY_STROITEL_2018_01" (TO_CHAR("LSO")) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS#DATA1" ;
