--------------------------------------------------------
--  DDL for Table KOTEL_OTHER_PRIH
--------------------------------------------------------

  CREATE TABLE "FCR"."KOTEL_OTHER_PRIH" 
   (	"ID" NUMBER(*,0), 
	"PL_SUM" NUMBER(38,2), 
	"PL_DATE" DATE, 
	"COMM" VARCHAR2(500 BYTE), 
	"C#OPS_ID" NUMBER, 
	"C#OSTATOK" NUMBER, 
	"ROW_TIME" TIMESTAMP (6) DEFAULT sysdate
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS#DATA1" ;
