--------------------------------------------------------
--  DDL for Table MV_HOUSES_ADRESES
--------------------------------------------------------

  CREATE TABLE "FCR"."MV_HOUSES_ADRESES" 
   (	"HOUSE_ID" NUMBER(*,0), 
	"ADDR" VARCHAR2(4000 BYTE), 
	"ADDR2" VARCHAR2(4000 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS#DATA1" ;
