CREATE OR REPLACE PACKAGE P#MN_UTILS
  IS

  FUNCTION GET#MN(A#DATE DATE)
    RETURN NUMBER DETERMINISTIC;
  
  FUNCTION GET#MN(A#YEAR  NUMBER,
                  A#MONTH NUMBER)
    RETURN NUMBER DETERMINISTIC;
  
  FUNCTION GET#DATE(A#MN NUMBER)
    RETURN DATE DETERMINISTIC;

  FUNCTION GET#PERIOD(A#MN NUMBER)
    RETURN VARCHAR2;
  
  FUNCTION GET#YEAR(A#MN NUMBER)
    RETURN NUMBER DETERMINISTIC;
  
  FUNCTION GET#MONTH(A#MN NUMBER)
    RETURN NUMBER DETERMINISTIC;

END;
/


CREATE OR REPLACE PACKAGE BODY P#MN_UTILS
  IS

  FUNCTION GET#MN(A#DATE DATE)
    RETURN NUMBER
    IS
    BEGIN
      RETURN MONTHS_BETWEEN(TRUNC(A#DATE, 'MM'), TO_DATE('0_12', 'YY_MM'));
    END;
  FUNCTION GET#MN(A#YEAR  NUMBER,
                  A#MONTH NUMBER)
    RETURN NUMBER
    IS
    BEGIN
      RETURN GET#MN(TO_DATE(A#YEAR || '_' || A#MONTH, 'YYYY_MM'));
    END;
  FUNCTION GET#DATE(A#MN NUMBER)
    RETURN DATE
    IS
    BEGIN
      RETURN ADD_MONTHS(TO_DATE('0_12', 'YY_MM'), TRUNC(A#MN));
    END;
  FUNCTION GET#YEAR(A#MN NUMBER)
    RETURN NUMBER
    IS
    BEGIN
      RETURN EXTRACT(YEAR FROM GET#DATE(A#MN));
    END;
  FUNCTION GET#MONTH(A#MN NUMBER)
    RETURN NUMBER
    IS
    BEGIN
      RETURN EXTRACT(MONTH FROM GET#DATE(A#MN));
    END;

  FUNCTION GET#PERIOD(A#MN NUMBER)
    RETURN VARCHAR2 AS
  BEGIN
    RETURN LPAD(P#MN_UTILS.GET#MONTH(A#MN),2,'0')||'.'||P#MN_UTILS.GET#YEAR(A#MN);
  END GET#PERIOD;

END;
/
