--------------------------------------------------------
--  DDL for Package P#MN_UTILS
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE "FCR"."P#MN_UTILS" 
  IS

  FUNCTION GET#MN(A#DATE DATE)
    RETURN NUMBER DETERMINISTIC;
  
  FUNCTION GET#MN(A#YEAR  NUMBER,
                  A#MONTH NUMBER)
    RETURN NUMBER DETERMINISTIC;
  
  FUNCTION GET#DATE(A#MN NUMBER)
    RETURN DATE DETERMINISTIC;

  FUNCTION GET#PERIOD(A#MN NUMBER)
    RETURN VARCHAR2;
  
  FUNCTION GET#YEAR(A#MN NUMBER)
    RETURN NUMBER DETERMINISTIC;
  
  FUNCTION GET#MONTH(A#MN NUMBER)
    RETURN NUMBER DETERMINISTIC;

END;

/
