--------------------------------------------------------
--  DDL for Table REGDOCS_OUTPUT
--------------------------------------------------------

  CREATE TABLE "FCR"."REGDOCS_OUTPUT" 
   (	"DATE_OUTPUT" DATE, 
	"NUM_OUTPUT" VARCHAR2(40 BYTE), 
	"ON_DATE_INP" DATE, 
	"ON_NUM_INP" VARCHAR2(40 BYTE), 
	"FROM_W" VARCHAR2(255 BYTE), 
	"THEME" VARCHAR2(255 BYTE), 
	"ISPOLNITEL" VARCHAR2(40 BYTE), 
	"STATUS" VARCHAR2(40 BYTE), 
	"C#ID" NUMBER(*,0), 
	"C#KEY" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS#DATA1" ;
