--------------------------------------------------------
--  DDL for Table T3_BANK
--------------------------------------------------------

  CREATE TABLE "FCR"."T3_BANK" 
   (	"C#ID" NUMBER(10,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE , 
	"C#NAME" VARCHAR2(50 BYTE), 
	"C#BIC_NUM" VARCHAR2(9 BYTE), 
	"C#CA_NUM" VARCHAR2(20 BYTE), 
	"C#TOWN_NAME" VARCHAR2(30 BYTE), 
	"C#KPP" VARCHAR2(20 BYTE), 
	"C#OGRN" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS#DATA1" ;

   COMMENT ON COLUMN "FCR"."T3_BANK"."C#NAME" IS 'наименование';
   COMMENT ON COLUMN "FCR"."T3_BANK"."C#BIC_NUM" IS 'БИК';
   COMMENT ON COLUMN "FCR"."T3_BANK"."C#CA_NUM" IS 'корсчет';
   COMMENT ON COLUMN "FCR"."T3_BANK"."C#TOWN_NAME" IS 'город';
   COMMENT ON COLUMN "FCR"."T3_BANK"."C#KPP" IS 'КПП';
   COMMENT ON COLUMN "FCR"."T3_BANK"."C#OGRN" IS 'ОГРН';
