--------------------------------------------------------
--  DDL for Table T3_CONTRACTORS
--------------------------------------------------------

  CREATE TABLE "FCR"."T3_CONTRACTORS" 
   (	"C#ID" NUMBER(10,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE , 
	"C#NAME" VARCHAR2(200 BYTE), 
	"C#INN" VARCHAR2(12 BYTE), 
	"C#KPP" VARCHAR2(9 BYTE), 
	"C#BANK_ACCOUNT" VARCHAR2(20 BYTE), 
	"C#CONTACT_INFO" VARCHAR2(250 BYTE), 
	"C#BANK_ID" NUMBER(10,0), 
	"C#1C_ID" VARCHAR2(20 BYTE), 
	"C#OGRN" VARCHAR2(13 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS#DATA1" ;

   COMMENT ON COLUMN "FCR"."T3_CONTRACTORS"."C#NAME" IS 'наименование';
   COMMENT ON COLUMN "FCR"."T3_CONTRACTORS"."C#INN" IS 'ИНН';
   COMMENT ON COLUMN "FCR"."T3_CONTRACTORS"."C#KPP" IS 'КПП';
   COMMENT ON COLUMN "FCR"."T3_CONTRACTORS"."C#BANK_ACCOUNT" IS 'номер банковского счета';
   COMMENT ON COLUMN "FCR"."T3_CONTRACTORS"."C#CONTACT_INFO" IS 'контактные данные';
   COMMENT ON COLUMN "FCR"."T3_CONTRACTORS"."C#BANK_ID" IS 'банк';
   COMMENT ON COLUMN "FCR"."T3_CONTRACTORS"."C#1C_ID" IS 'айдишник из 1С
';
   COMMENT ON COLUMN "FCR"."T3_CONTRACTORS"."C#OGRN" IS 'ОГРН';
   COMMENT ON TABLE "FCR"."T3_CONTRACTORS"  IS 'подрядчики';
