--------------------------------------------------------
--  Constraints for Table T3_CONTRACTS
--------------------------------------------------------

  ALTER TABLE "FCR"."T3_CONTRACTS" MODIFY ("C#ID" NOT NULL ENABLE);
  ALTER TABLE "FCR"."T3_CONTRACTS" ADD CONSTRAINT "PK_T3_CONTRACTS_C#ID" PRIMARY KEY ("C#ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS#DATA1"  ENABLE;
  ALTER TABLE "FCR"."T3_CONTRACTS" ADD CONSTRAINT "T3_CONTRACTS_UK1" UNIQUE ("C#DATE", "C#NUM", "C#CONTRACT_TYPE_ID", "C#CONTRACTOR_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS#DATA1"  ENABLE;
