--------------------------------------------------------
--  DDL for Table T3_ELEMENTS
--------------------------------------------------------

  CREATE TABLE "FCR"."T3_ELEMENTS" 
   (	"C#ID" NUMBER(10,0), 
	"C#NAME" VARCHAR2(150 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS#DATA1" ;

   COMMENT ON COLUMN "FCR"."T3_ELEMENTS"."C#ID" IS '';
   COMMENT ON COLUMN "FCR"."T3_ELEMENTS"."C#NAME" IS 'наименование';
   COMMENT ON TABLE "FCR"."T3_ELEMENTS"  IS 'типы оплат работ по капремонту';
