--------------------------------------------------------
--  DDL for Table T3_JOB_TYPE
--------------------------------------------------------

  CREATE TABLE "FCR"."T3_JOB_TYPE" 
   (	"C#ID" NUMBER(10,0), 
	"C#NAME" VARCHAR2(200 BYTE), 
	"C#REG_JOB_TYPE_ID" NUMBER(10,0), 
	"C#ELEM_CODE" NUMBER(10,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS#DATA1" ;

   COMMENT ON COLUMN "FCR"."T3_JOB_TYPE"."C#NAME" IS 'наименование';
   COMMENT ON COLUMN "FCR"."T3_JOB_TYPE"."C#REG_JOB_TYPE_ID" IS 'региональный 
код работ';
   COMMENT ON COLUMN "FCR"."T3_JOB_TYPE"."C#ELEM_CODE" IS 'код конструктивного елемента для типа работ';
   COMMENT ON TABLE "FCR"."T3_JOB_TYPE"  IS 'типы работ по капремонту';
