--------------------------------------------------------
--  DDL for Trigger T3_JOBS_PLAN_TRG1
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "FCR"."T3_JOBS_PLAN_TRG1" 
BEFORE INSERT ON T3_JOBS_PLAN 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.C#ID IS NULL THEN
      SELECT T3_JOBS_PLAN_SEQ2.NEXTVAL INTO :NEW.C#ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "FCR"."T3_JOBS_PLAN_TRG1" ENABLE;
