--------------------------------------------------------
--  DDL for Table T3_JOBS
--------------------------------------------------------

  CREATE TABLE "FCR"."T3_JOBS" 
   (	"C#ID" NUMBER(10,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE , 
	"C#JOB_TYPE_ID" NUMBER(10,0), 
	"C#CONTRACT_ID" NUMBER(10,0), 
	"C#DATE_BEGIN" DATE, 
	"C#DATE_END" DATE, 
	"C#NOTE" VARCHAR2(250 BYTE), 
	"C#HOUSE_ID" NUMBER(10,0), 
	"C#STATUS" VARCHAR2(10 BYTE) DEFAULT 'WORK'
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS#DATA1" ;

   COMMENT ON COLUMN "FCR"."T3_JOBS"."C#JOB_TYPE_ID" IS 'тип работ';
   COMMENT ON COLUMN "FCR"."T3_JOBS"."C#CONTRACT_ID" IS 'договор';
   COMMENT ON COLUMN "FCR"."T3_JOBS"."C#DATE_BEGIN" IS 'дата начала работ';
   COMMENT ON COLUMN "FCR"."T3_JOBS"."C#DATE_END" IS 'дата окончания работ';
   COMMENT ON COLUMN "FCR"."T3_JOBS"."C#NOTE" IS 'примечание';
   COMMENT ON COLUMN "FCR"."T3_JOBS"."C#HOUSE_ID" IS 'дом';
   COMMENT ON COLUMN "FCR"."T3_JOBS"."C#STATUS" IS 'статус работ (PLAN, WORK, OK, CANCEL
)';
   COMMENT ON TABLE "FCR"."T3_JOBS"  IS 'работы по капремонту';
