--------------------------------------------------------
--  DDL for Table T3_JOBS_PLAN
--------------------------------------------------------

  CREATE TABLE "FCR"."T3_JOBS_PLAN" 
   (	"C#ID" NUMBER(10,0), 
	"C#REG_JOB_TYPE_ID" NUMBER(10,0), 
	"C#REC_DATE" DATE DEFAULT sysdate, 
	"C#YEAR_BEG" NUMBER(4,0), 
	"C#NOTE" VARCHAR2(250 BYTE), 
	"C#HOUSE_ID" NUMBER(10,0), 
	"C#SUMM" NUMBER DEFAULT 0, 
	"C#YEAR_END" NUMBER(4,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS#DATA1" ;

   COMMENT ON COLUMN "FCR"."T3_JOBS_PLAN"."C#ID" IS '';
   COMMENT ON COLUMN "FCR"."T3_JOBS_PLAN"."C#REG_JOB_TYPE_ID" IS 'тип работ';
   COMMENT ON COLUMN "FCR"."T3_JOBS_PLAN"."C#REC_DATE" IS 'дата добавления записи';
   COMMENT ON COLUMN "FCR"."T3_JOBS_PLAN"."C#YEAR_BEG" IS 'плановый год начала рабjn';
   COMMENT ON COLUMN "FCR"."T3_JOBS_PLAN"."C#NOTE" IS 'примечание';
   COMMENT ON COLUMN "FCR"."T3_JOBS_PLAN"."C#HOUSE_ID" IS 'дом';
   COMMENT ON COLUMN "FCR"."T3_JOBS_PLAN"."C#SUMM" IS 'плановая сумма по работе';
   COMMENT ON COLUMN "FCR"."T3_JOBS_PLAN"."C#YEAR_END" IS 'плановый год окончания работ
';
   COMMENT ON TABLE "FCR"."T3_JOBS_PLAN"  IS 'плановые работы по капремонту';
