--------------------------------------------------------
--  Constraints for Table T3_JOBS
--------------------------------------------------------

  ALTER TABLE "FCR"."T3_JOBS" MODIFY ("C#ID" NOT NULL ENABLE);
  ALTER TABLE "FCR"."T3_JOBS" ADD CONSTRAINT "PK_T3_JOBS_C#ID" PRIMARY KEY ("C#ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS#DATA1"  ENABLE;
  ALTER TABLE "FCR"."T3_JOBS" ADD CONSTRAINT "T3_JOBS_STATUS_CHECK" CHECK (upper(C#STATUS) in ('PLAN','WORK','OK','CANCEL')) ENABLE;
  ALTER TABLE "FCR"."T3_JOBS" ADD CONSTRAINT "T3_JOBS_UK1" UNIQUE ("C#JOB_TYPE_ID", "C#CONTRACT_ID", "C#HOUSE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS#DATA1"  ENABLE;
