--------------------------------------------------------
--  DDL for Index T3_PAY_UK1
--------------------------------------------------------

  CREATE UNIQUE INDEX "FCR"."T3_PAY_UK1" ON "FCR"."T3_PAY" ("C#PAY_TYPE_ID", "C#SOURCE", "C#SUM", "C#JOB_ID", "C#PAY_DATE", "C#INVOICE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS#DATA1" ;
