--------------------------------------------------------
--  DDL for Table T3_PAY_IMPORT
--------------------------------------------------------

  CREATE TABLE "FCR"."T3_PAY_IMPORT" 
   (	"DATA_PL" DATE, 
	"SUMM_PL" NUMBER(11,2), 
	"PD_NUM" VARCHAR2(6 BYTE), 
	"INN" VARCHAR2(12 BYTE), 
	"PLAT" VARCHAR2(500 BYTE), 
	"PRIM" VARCHAR2(500 BYTE), 
	"ID_HOUSE" NUMBER(10,0), 
	"TIP_WORK" NUMBER(4,0), 
	"DOGOVOR_DA" DATE, 
	"DOGOVOR_NU" VARCHAR2(26 BYTE), 
	"TIP_PL" NUMBER(3,0), 
	"SOURCE" VARCHAR2(20 BYTE) DEFAULT 'OWNERS', 
	"STATUS" VARCHAR2(20 BYTE) DEFAULT 'WORK', 
	"ITEM_DATE" DATE DEFAULT sysdate
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS#DATA1" ;
