--------------------------------------------------------
--  Constraints for Table T3_PAY
--------------------------------------------------------

  ALTER TABLE "FCR"."T3_PAY" MODIFY ("C#ID" NOT NULL ENABLE);
  ALTER TABLE "FCR"."T3_PAY" ADD CONSTRAINT "T3_PAY_PK" PRIMARY KEY ("C#ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS#DATA1"  ENABLE;
  ALTER TABLE "FCR"."T3_PAY" ADD CONSTRAINT "T3_PAY_CHK_SOURCE" CHECK (UPPER(C#SOURCE) IN ('GOS','OWNERS','CREDIT')) ENABLE;
  ALTER TABLE "FCR"."T3_PAY" ADD CONSTRAINT "T3_PAY_UK1" UNIQUE ("C#PAY_TYPE_ID", "C#SOURCE", "C#SUM", "C#JOB_ID", "C#PAY_DATE", "C#INVOICE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS#DATA1"  ENABLE;
