--------------------------------------------------------
--  Constraints for Table T3_PAY_IMPORT
--------------------------------------------------------

  ALTER TABLE "FCR"."T3_PAY_IMPORT" MODIFY ("DATA_PL" NOT NULL ENABLE);
  ALTER TABLE "FCR"."T3_PAY_IMPORT" MODIFY ("SUMM_PL" NOT NULL ENABLE);
  ALTER TABLE "FCR"."T3_PAY_IMPORT" MODIFY ("PD_NUM" NOT NULL ENABLE);
  ALTER TABLE "FCR"."T3_PAY_IMPORT" MODIFY ("INN" NOT NULL ENABLE);
  ALTER TABLE "FCR"."T3_PAY_IMPORT" MODIFY ("ID_HOUSE" NOT NULL ENABLE);
  ALTER TABLE "FCR"."T3_PAY_IMPORT" MODIFY ("TIP_WORK" NOT NULL ENABLE);
  ALTER TABLE "FCR"."T3_PAY_IMPORT" MODIFY ("DOGOVOR_DA" NOT NULL ENABLE);
  ALTER TABLE "FCR"."T3_PAY_IMPORT" MODIFY ("DOGOVOR_NU" NOT NULL ENABLE);
  ALTER TABLE "FCR"."T3_PAY_IMPORT" MODIFY ("TIP_PL" NOT NULL ENABLE);
