--------------------------------------------------------
--  DDL for Table T3_PAY
--------------------------------------------------------

  CREATE TABLE "FCR"."T3_PAY" 
   (	"C#ID" NUMBER(10,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE , 
	"C#PAY_TYPE_ID" NUMBER(10,0), 
	"C#SOURCE" VARCHAR2(10 BYTE) DEFAULT 'OWNERS', 
	"C#SUM" NUMBER(*,2), 
	"C#JOB_ID" NUMBER(10,0), 
	"C#INVOICE" VARCHAR2(10 BYTE), 
	"C#PAY_DATE" DATE, 
	"C#NOTE" VARCHAR2(500 BYTE), 
	"ROW_TIME" TIMESTAMP (6) DEFAULT sysdate
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS#DATA1" ;

   COMMENT ON COLUMN "FCR"."T3_PAY"."C#PAY_TYPE_ID" IS 'тип платежа';
   COMMENT ON COLUMN "FCR"."T3_PAY"."C#SOURCE" IS 'источник средств (GOS,OWNERS,CREDIT)';
   COMMENT ON COLUMN "FCR"."T3_PAY"."C#SUM" IS 'сумма';
   COMMENT ON COLUMN "FCR"."T3_PAY"."C#JOB_ID" IS 'работа';
   COMMENT ON COLUMN "FCR"."T3_PAY"."C#INVOICE" IS '№ платежки из 1С';
   COMMENT ON COLUMN "FCR"."T3_PAY"."C#PAY_DATE" IS 'дата платежа';
   COMMENT ON COLUMN "FCR"."T3_PAY"."C#NOTE" IS 'примечание';
   COMMENT ON TABLE "FCR"."T3_PAY"  IS 'платежи по работам';
