--------------------------------------------------------
--  DDL for Table T3_REG_JOB_TYPE
--------------------------------------------------------

  CREATE TABLE "FCR"."T3_REG_JOB_TYPE" 
   (	"C#ID" NUMBER(10,0), 
	"C#NAME" VARCHAR2(100 BYTE), 
	"HOUSE_INFO_FIELD_NAME" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS#DATA1" ;
