--------------------------------------------------------
--  DDL for Table T3_TEMP_BARTER
--------------------------------------------------------

  CREATE TABLE "FCR"."T3_TEMP_BARTER" 
   (	"ADDR" VARCHAR2(200 BYTE), 
	"JOB_TYPE" VARCHAR2(128 BYTE), 
	"SUMMA" NUMBER, 
	"BARTER_DATE" DATE, 
	"HOUSE_ID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS#DATA1" ;
