--------------------------------------------------------
--  DDL for Table T3_TEMP_GOS
--------------------------------------------------------

  CREATE TABLE "FCR"."T3_TEMP_GOS" 
   (	"NN" NUMBER(4,0), 
	"HOUSE_ID" NUMBER(26,0), 
	"DATA_PL" DATE, 
	"SUMM_PL" NUMBER(11,2), 
	"TIP_OPL" VARCHAR2(50 BYTE), 
	"PD_NUM" NUMBER(6,0), 
	"INN" VARCHAR2(14 BYTE), 
	"PLAT" VARCHAR2(256 BYTE), 
	"TIP_PL" VARCHAR2(26 BYTE), 
	"N_DOG" VARCHAR2(26 BYTE), 
	"DATE_DOG" DATE, 
	"VID_REM" VARCHAR2(128 BYTE), 
	"DOM" VARCHAR2(26 BYTE), 
	"UL" VARCHAR2(128 BYTE), 
	"TIP" VARCHAR2(26 BYTE), 
	"TOWN" VARCHAR2(26 BYTE), 
	"FULLADR" VARCHAR2(128 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS#DATA1" ;
