--------------------------------------------------------
--  DDL for Table T3_TEMP_BOG
--------------------------------------------------------

  CREATE TABLE "FCR"."T3_TEMP_BOG" 
   (	"DATA_PL" VARCHAR2(26 BYTE), 
	"SUMM_PL" VARCHAR2(26 BYTE), 
	"PD_NUM" VARCHAR2(26 BYTE), 
	"INN" VARCHAR2(26 BYTE), 
	"TIP_OPL" VARCHAR2(21 BYTE), 
	"N_DOG" VARCHAR2(26 BYTE), 
	"DATA_DOG" VARCHAR2(11 BYTE), 
	"VID_RABOT" VARCHAR2(128 BYTE), 
	"NN" VARCHAR2(26 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS#DATA1" ;
