--------------------------------------------------------
--  DDL for Table T3_TEMP_KAN_SOURCE
--------------------------------------------------------

  CREATE TABLE "FCR"."T3_TEMP_KAN_SOURCE" 
   (	"NN" NUMBER, 
	"HOUSE_ID" VARCHAR2(100 BYTE), 
	"PRIM" VARCHAR2(2000 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS#DATA1" ;
