--------------------------------------------------------
--  DDL for Table T3_TEMP_JOBS_1C
--------------------------------------------------------

  CREATE TABLE "FCR"."T3_TEMP_JOBS_1C" 
   (	"DATA_PL" DATE, 
	"SUMM_PL" NUMBER(38,2), 
	"PENALTY" NUMBER(38,0), 
	"LS" VARCHAR2(26 BYTE), 
	"PERIOD" VARCHAR2(26 BYTE), 
	"COD_RKC" VARCHAR2(26 BYTE), 
	"PD_NUM" NUMBER(38,0), 
	"INN" VARCHAR2(20 BYTE), 
	"KPP" VARCHAR2(20 BYTE), 
	"PLAT" VARCHAR2(500 BYTE), 
	"PRIM" VARCHAR2(2000 BYTE), 
	"NN" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS#DATA1" ;
