--------------------------------------------------------
--  DDL for Table T3_TEMP_PAY
--------------------------------------------------------

  CREATE TABLE "FCR"."T3_TEMP_PAY" 
   (	"PAY_ID" NUMBER(6,0), 
	"JOB_ID" NUMBER(6,0), 
	"HOUSE_ID" NUMBER(6,0), 
	"ADDR" VARCHAR2(128 BYTE), 
	"SOURCE" VARCHAR2(26 BYTE), 
	"SUMMA" NUMBER(11,2), 
	"PAY_DATE" VARCHAR2(26 BYTE), 
	"INVOICE" VARCHAR2(10 BYTE), 
	"OLD_TYPE" VARCHAR2(128 BYTE), 
	"NEW_TYPE" VARCHAR2(256 BYTE), 
	"NOTE" VARCHAR2(1024 BYTE), 
	"CONTRACT_ID" NUMBER(10,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS#DATA1" ;
