--------------------------------------------------------
--  DDL for Table T3_TEMP_SPEC
--------------------------------------------------------

  CREATE TABLE "FCR"."T3_TEMP_SPEC" 
   (	"HOUSE_ID" NUMBER, 
	"SUMM" NUMBER, 
	"KONTR" VARCHAR2(128 BYTE), 
	"INN" VARCHAR2(26 BYTE), 
	"PD_NUM" VARCHAR2(26 BYTE), 
	"DN_PAY" DATE, 
	"TIP_PL" VARCHAR2(18 BYTE), 
	"N_DOG" VARCHAR2(26 BYTE), 
	"DT_DOG" DATE, 
	"VIR_RAB" VARCHAR2(128 BYTE), 
	"TOWN" VARCHAR2(26 BYTE), 
	"UL" VARCHAR2(26 BYTE), 
	"HOUSE" VARCHAR2(26 BYTE), 
	"ADDR" VARCHAR2(128 BYTE), 
	"PRIM" VARCHAR2(1024 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS#DATA1" ;
