--------------------------------------------------------
--  DDL for Table T4_HOUSE_PROTS
--------------------------------------------------------

  CREATE TABLE "FCR"."T4_HOUSE_PROTS" 
   (	"C#ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE , 
	"C#VER" NUMBER, 
	"C#NUM" VARCHAR2(50 BYTE), 
	"C#DATE" DATE, 
	"C#HOUSE_ID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS#DATA1" ;

   COMMENT ON COLUMN "FCR"."T4_HOUSE_PROTS"."C#VER" IS 'версия';
   COMMENT ON COLUMN "FCR"."T4_HOUSE_PROTS"."C#NUM" IS '№ протокола';
   COMMENT ON COLUMN "FCR"."T4_HOUSE_PROTS"."C#DATE" IS 'дата протокола';
   COMMENT ON COLUMN "FCR"."T4_HOUSE_PROTS"."C#HOUSE_ID" IS 'дом';
