--------------------------------------------------------
--  Constraints for Table T4_HOUSE_PROTS
--------------------------------------------------------

  ALTER TABLE "FCR"."T4_HOUSE_PROTS" MODIFY ("C#ID" NOT NULL ENABLE);
  ALTER TABLE "FCR"."T4_HOUSE_PROTS" ADD CONSTRAINT "T4_HOUSE_PROTS_PK" PRIMARY KEY ("C#ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS#DATA1"  ENABLE;
  ALTER TABLE "FCR"."T4_HOUSE_PROTS" MODIFY ("C#HOUSE_ID" NOT NULL ENABLE);
  ALTER TABLE "FCR"."T4_HOUSE_PROTS" ADD CONSTRAINT "T4_HOUSE_PROTS_UK1" UNIQUE ("C#HOUSE_ID", "C#NUM", "C#DATE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS#DATA1"  ENABLE;
