--------------------------------------------------------
--  DDL for Trigger T4_PAY_TO_HOSTS_TRG1
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "FCR"."T4_PAY_TO_HOSTS_TRG1" 
BEFORE INSERT ON "T4_TRANSFER" 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.C#ID IS NULL THEN
      SELECT T4_PAY_TO_HOSTS_SEQ1.NEXTVAL INTO :NEW.C#ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "FCR"."T4_PAY_TO_HOSTS_TRG1" ENABLE;
