--------------------------------------------------------
--  Constraints for Table T4_SPEC_ACCOUNTS
--------------------------------------------------------

  ALTER TABLE "FCR"."T4_SPEC_ACCOUNTS" MODIFY ("C#ID" NOT NULL ENABLE);
  ALTER TABLE "FCR"."T4_SPEC_ACCOUNTS" MODIFY ("C#ACC_NUM" NOT NULL ENABLE);
  ALTER TABLE "FCR"."T4_SPEC_ACCOUNTS" ADD CONSTRAINT "T4_SPEC_ACCOUNTS_PK" PRIMARY KEY ("C#ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS#DATA1"  ENABLE;
  ALTER TABLE "FCR"."T4_SPEC_ACCOUNTS" MODIFY ("C#ACC_HOST_ID" NOT NULL ENABLE);
  ALTER TABLE "FCR"."T4_SPEC_ACCOUNTS" ADD CONSTRAINT "T4_SPEC_ACCOUNTS_UK1" UNIQUE ("C#ACC_HOST_ID", "C#ACC_NUM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS#DATA1"  ENABLE;
