--------------------------------------------------------
--  DDL for Trigger T4_SPEC_ACCOUNTS_TRG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "FCR"."T4_SPEC_ACCOUNTS_TRG" 
BEFORE INSERT ON T4_SPEC_ACCOUNTS 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.C#ID IS NULL THEN
      SELECT T4_SPEC_ACCOUNTS_SEQ2.NEXTVAL INTO :NEW.C#ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "FCR"."T4_SPEC_ACCOUNTS_TRG" ENABLE;
