--------------------------------------------------------
--  DDL for Table T4_TRANSFER
--------------------------------------------------------

  CREATE TABLE "FCR"."T4_TRANSFER" 
   (	"C#ID" NUMBER(10,0), 
	"C#SUM" NUMBER(*,2), 
	"C#INVOICE" VARCHAR2(10 BYTE), 
	"C#DATE" DATE, 
	"C#NOTE" VARCHAR2(1000 BYTE), 
	"C#HOUSE_ID" NUMBER, 
	"C#ACC_FROM" VARCHAR2(20 BYTE), 
	"C#ACC_TO" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS#DATA1" ;

   COMMENT ON COLUMN "FCR"."T4_TRANSFER"."C#ID" IS '';
   COMMENT ON COLUMN "FCR"."T4_TRANSFER"."C#SUM" IS 'сумма';
   COMMENT ON COLUMN "FCR"."T4_TRANSFER"."C#INVOICE" IS '№ платежки из 1С';
   COMMENT ON COLUMN "FCR"."T4_TRANSFER"."C#DATE" IS 'дата перевода';
   COMMENT ON COLUMN "FCR"."T4_TRANSFER"."C#NOTE" IS 'примечание';
   COMMENT ON TABLE "FCR"."T4_TRANSFER"  IS 'переводы укашкам';
