--------------------------------------------------------
--  DDL for Table T#ACCOUNT
--------------------------------------------------------

  CREATE TABLE "FCR"."T#ACCOUNT" 
   (	"C#ID" NUMBER(*,0), 
	"C#ROOMS_ID" NUMBER(*,0), 
	"C#ROOMS_PN" NUMBER(*,0), 
	"C#DATE" DATE, 
	"C#NUM" VARCHAR2(20 BYTE), 
	"C#SN" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS#DATA1" ;

   COMMENT ON COLUMN "FCR"."T#ACCOUNT"."C#NUM" IS 'Номер.';
   COMMENT ON COLUMN "FCR"."T#ACCOUNT"."C#SN" IS 'Порядковый номер.';
