--------------------------------------------------------
--  Constraints for Table T#ACCOUNT_OP
--------------------------------------------------------

  ALTER TABLE "FCR"."T#ACCOUNT_OP" MODIFY ("C#ACCOUNT_ID" NOT NULL ENABLE);
  ALTER TABLE "FCR"."T#ACCOUNT_OP" MODIFY ("C#DATE" NOT NULL ENABLE);
  ALTER TABLE "FCR"."T#ACCOUNT_OP" ADD CONSTRAINT "CP#ACCOUNT_OP" PRIMARY KEY ("C#ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS#DATA1"  ENABLE;
  ALTER TABLE "FCR"."T#ACCOUNT_OP" ADD CONSTRAINT "CU#ACCOUNT_OP" UNIQUE ("C#ACCOUNT_ID", "C#DATE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS#DATA1"  ENABLE;
