--------------------------------------------------------
--  Constraints for Table T#ACCOUNT
--------------------------------------------------------

  ALTER TABLE "FCR"."T#ACCOUNT" MODIFY ("C#ROOMS_ID" NOT NULL ENABLE);
  ALTER TABLE "FCR"."T#ACCOUNT" MODIFY ("C#ROOMS_PN" NOT NULL ENABLE);
  ALTER TABLE "FCR"."T#ACCOUNT" MODIFY ("C#DATE" NOT NULL ENABLE);
  ALTER TABLE "FCR"."T#ACCOUNT" MODIFY ("C#NUM" NOT NULL ENABLE);
  ALTER TABLE "FCR"."T#ACCOUNT" MODIFY ("C#SN" NOT NULL ENABLE);
  ALTER TABLE "FCR"."T#ACCOUNT" ADD CONSTRAINT "CP#ACCOUNT" PRIMARY KEY ("C#ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS#DATA1"  ENABLE;
  ALTER TABLE "FCR"."T#ACCOUNT" ADD CONSTRAINT "CU#ACCOUNT#1" UNIQUE ("C#ROOMS_ID", "C#ROOMS_PN", "C#DATE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS#DATA1"  ENABLE;
  ALTER TABLE "FCR"."T#ACCOUNT" ADD CONSTRAINT "CU#ACCOUNT#2" UNIQUE ("C#NUM", "C#SN")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS#DATA1"  ENABLE;
