--------------------------------------------------------
--  DDL for Table T_ADDROBJ68
--------------------------------------------------------

  CREATE TABLE "FCR"."T_ADDROBJ68" 
   (	"ACTSTATUS" NUMBER(*,0), 
	"AOGUID" VARCHAR2(36 BYTE), 
	"AOID" VARCHAR2(36 BYTE), 
	"AOLEVEL" NUMBER(*,0), 
	"AREACODE" VARCHAR2(3 BYTE), 
	"AUTOCODE" VARCHAR2(1 BYTE), 
	"CENTSTATUS" NUMBER(*,0), 
	"CITYCODE" VARCHAR2(3 BYTE), 
	"CODE" VARCHAR2(17 BYTE), 
	"CURRSTATUS" NUMBER(*,0), 
	"ENDDATE" DATE, 
	"FORMALNAME" VARCHAR2(120 BYTE), 
	"IFNSFL" VARCHAR2(4 BYTE), 
	"IFNSUL" VARCHAR2(4 BYTE), 
	"NEXTID" VARCHAR2(36 BYTE), 
	"OFFNAME" VARCHAR2(120 BYTE), 
	"OKATO" VARCHAR2(11 BYTE), 
	"OKTMO" VARCHAR2(11 BYTE), 
	"OPERSTATUS" NUMBER(*,0), 
	"PARENTGUID" VARCHAR2(36 BYTE), 
	"PLACECODE" VARCHAR2(3 BYTE), 
	"PLAINCODE" VARCHAR2(15 BYTE), 
	"POSTALCODE" VARCHAR2(6 BYTE), 
	"PREVID" VARCHAR2(36 BYTE), 
	"REGIONCODE" VARCHAR2(2 BYTE), 
	"SHORTNAME" VARCHAR2(10 BYTE), 
	"STARTDATE" DATE, 
	"STREETCODE" VARCHAR2(4 BYTE), 
	"TERRIFNSFL" VARCHAR2(4 BYTE), 
	"TERRIFNSUL" VARCHAR2(4 BYTE), 
	"UPDATEDATE" DATE, 
	"CTARCODE" VARCHAR2(3 BYTE), 
	"EXTRCODE" VARCHAR2(4 BYTE), 
	"SEXTCODE" VARCHAR2(3 BYTE), 
	"LIVESTATUS" NUMBER(*,0), 
	"NORMDOC" VARCHAR2(36 BYTE), 
	"PLANCODE" VARCHAR2(4 BYTE), 
	"CADNUM" VARCHAR2(100 BYTE), 
	"DIVTYPE" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS#DATA1" ;
