--------------------------------------------------------
--  DDL for Table T_ADDRESS
--------------------------------------------------------

  CREATE TABLE "FCR"."T_ADDRESS" 
   (	"C_ID" NUMBER(10,0), 
	"C_ADDRESS" VARCHAR2(255 BYTE), 
	"C_INDEX" VARCHAR2(6 BYTE), 
	"C_REGION" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS#DATA1" ;
