--------------------------------------------------------
--  Constraints for Table T#ADDR_OBJ
--------------------------------------------------------

  ALTER TABLE "FCR"."T#ADDR_OBJ" ADD CONSTRAINT "CC#ADDR_OBJ#FG" CHECK (regexp_like(C#FIAS_GUID,'^[0-9a-f]{8}-([0-9a-f]{4}-){3}[0-9a-f]{12}$')) ENABLE;
  ALTER TABLE "FCR"."T#ADDR_OBJ" ADD CONSTRAINT "CC#ADDR_OBJ#RFT" CHECK (C#R_FORM_TAG in ('N','Y')) ENABLE;
  ALTER TABLE "FCR"."T#ADDR_OBJ" ADD CONSTRAINT "CC#ADDR_OBJ#LT" CHECK (C#LEVEL_TAG in (1,2,3,4,5,6,7,65,90,91)) ENABLE;
  ALTER TABLE "FCR"."T#ADDR_OBJ" MODIFY ("C#TYPE_ID" NOT NULL ENABLE);
  ALTER TABLE "FCR"."T#ADDR_OBJ" MODIFY ("C#LEVEL_TAG" NOT NULL ENABLE);
  ALTER TABLE "FCR"."T#ADDR_OBJ" MODIFY ("C#CENTER_TAG" NOT NULL ENABLE);
  ALTER TABLE "FCR"."T#ADDR_OBJ" MODIFY ("C#NAME" NOT NULL ENABLE);
  ALTER TABLE "FCR"."T#ADDR_OBJ" ADD CONSTRAINT "CC#ADDR_OBJ#CT" CHECK (C#CENTER_TAG in (0,1,2,3)) ENABLE;
  ALTER TABLE "FCR"."T#ADDR_OBJ" ADD CONSTRAINT "CP#ADDR_OBJ" PRIMARY KEY ("C#ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS#DATA1"  ENABLE;
