--------------------------------------------------------
--  DDL for Table T#ARM_OBJEKTS
--------------------------------------------------------

  CREATE TABLE "FCR"."T#ARM_OBJEKTS" 
   (	"C#ADDROBJ_ID" VARCHAR2(200 BYTE), 
	"C#ACCOUNT_ID" VARCHAR2(20 BYTE), 
	"C#HOUSE_ID" VARCHAR2(20 BYTE), 
	"C#PERSON_ID" VARCHAR2(20 BYTE), 
	"C#ROOM_ID" VARCHAR2(20 BYTE), 
	"C#OUT_AC_NUM" VARCHAR2(20 BYTE), 
	"C#AC_NUM" VARCHAR2(20 BYTE), 
	"C#ADR" VARCHAR2(100 BYTE), 
	"C#HOUS_NUM" VARCHAR2(20 BYTE), 
	"C#FLAT_NUM" VARCHAR2(20 BYTE), 
	"C#PERSON_NAME" VARCHAR2(200 BYTE), 
	"C#ID_ISPOLN" NUMBER, 
	"C#ID_TASK" NUMBER, 
	"C#KEY" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS#DATA1" ;
  GRANT FLASHBACK ON "FCR"."T#ARM_OBJEKTS" TO "KAN";
  GRANT DEBUG ON "FCR"."T#ARM_OBJEKTS" TO "KAN";
  GRANT QUERY REWRITE ON "FCR"."T#ARM_OBJEKTS" TO "KAN";
  GRANT ON COMMIT REFRESH ON "FCR"."T#ARM_OBJEKTS" TO "KAN";
