--------------------------------------------------------
--  DDL for Table T#ARM
--------------------------------------------------------

  CREATE TABLE "FCR"."T#ARM" 
   (	"C#ID" NUMBER, 
	"C#DOC_TYPE" VARCHAR2(20 BYTE), 
	"C#AUTHOR" VARCHAR2(20 BYTE), 
	"C#WORK_TYPE" VARCHAR2(20 BYTE), 
	"C#PARENT_ID" NUMBER, 
	"C#OWNER" VARCHAR2(20 BYTE), 
	"C#AL_STATUS" VARCHAR2(20 BYTE), 
	"C#BEGIN_DATE" DATE, 
	"C#END_DATE" DATE, 
	"C#SEND_TO_MAIL" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS#DATA1" ;
  GRANT FLASHBACK ON "FCR"."T#ARM" TO "KAN";
  GRANT DEBUG ON "FCR"."T#ARM" TO "KAN";
  GRANT QUERY REWRITE ON "FCR"."T#ARM" TO "KAN";
  GRANT ON COMMIT REFRESH ON "FCR"."T#ARM" TO "KAN";
  GRANT REFERENCES ON "FCR"."T#ARM" TO "KAN";
  GRANT UPDATE ON "FCR"."T#ARM" TO "KAN";
  GRANT SELECT ON "FCR"."T#ARM" TO "KAN";
  GRANT INSERT ON "FCR"."T#ARM" TO "KAN";
  GRANT INDEX ON "FCR"."T#ARM" TO "KAN";
  GRANT DELETE ON "FCR"."T#ARM" TO "KAN";
  GRANT ALTER ON "FCR"."T#ARM" TO "KAN";
