--------------------------------------------------------
--  DDL for Table T#ARM_TASKS
--------------------------------------------------------

  CREATE TABLE "FCR"."T#ARM_TASKS" 
   (	"C#ID" NUMBER, 
	"C#SUB_TASK" VARCHAR2(500 BYTE), 
	"C#STATUS" VARCHAR2(20 BYTE), 
	"C#BEGIN_DATE" DATE, 
	"C#END_DATE" DATE, 
	"C#KEY" NUMBER, 
	"C#SEND_TO_MAIL" VARCHAR2(20 BYTE), 
	"C#AUTHOR" VARCHAR2(20 BYTE), 
	"C#ISPOLNITEL" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS#DATA1" ;
  GRANT FLASHBACK ON "FCR"."T#ARM_TASKS" TO "KAN";
  GRANT DEBUG ON "FCR"."T#ARM_TASKS" TO "KAN";
  GRANT QUERY REWRITE ON "FCR"."T#ARM_TASKS" TO "KAN";
  GRANT ON COMMIT REFRESH ON "FCR"."T#ARM_TASKS" TO "KAN";
