--------------------------------------------------------
--  DDL for Table T#B_OP
--------------------------------------------------------

  CREATE TABLE "FCR"."T#B_OP" 
   (	"C#ID" NUMBER(*,0), 
	"C#OPS_ID" NUMBER(*,0), 
	"C#HOUSE_ID" NUMBER(*,0), 
	"C#SERVICE_ID" NUMBER(*,0), 
	"C#B_ACCOUNT_ID" NUMBER(*,0), 
	"C#DATE" DATE, 
	"C#REAL_DATE" DATE, 
	"C#TYPE_TAG" VARCHAR2(2 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 8192 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS#DATA1" ;

   COMMENT ON COLUMN "FCR"."T#B_OP"."C#TYPE_TAG" IS 'Тип {"M":изменение;"P":платеж;"T":трансфер.}';
