--------------------------------------------------------
--  DDL for Table T#B_ACCOUNT
--------------------------------------------------------

  CREATE TABLE "FCR"."T#B_ACCOUNT" 
   (	"C#ID" NUMBER(*,0), 
	"C#BANK_ID" NUMBER(*,0), 
	"C#NUM" VARCHAR2(20 BYTE), 
	"C#NAME" VARCHAR2(100 BYTE), 
	"C#INN_NUM" VARCHAR2(12 BYTE), 
	"C#KPP_NUM" VARCHAR2(9 BYTE), 
	"C#ACC_TYPE" NUMBER(3,0), 
	"C#PROT_N" VARCHAR2(20 BYTE), 
	"C#PROT_DATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS#DATA1" ;

   COMMENT ON COLUMN "FCR"."T#B_ACCOUNT"."C#NUM" IS 'Номер.';
   COMMENT ON COLUMN "FCR"."T#B_ACCOUNT"."C#NAME" IS 'Наименование (получатель).';
   COMMENT ON COLUMN "FCR"."T#B_ACCOUNT"."C#INN_NUM" IS 'ИНН.';
   COMMENT ON COLUMN "FCR"."T#B_ACCOUNT"."C#KPP_NUM" IS 'КПП.';
   COMMENT ON COLUMN "FCR"."T#B_ACCOUNT"."C#ACC_TYPE" IS '1-Котел, 2 - Спецсчет, 50 - счет ТСЖ (пока 50 счет при формировании не выгружаем)';
   COMMENT ON COLUMN "FCR"."T#B_ACCOUNT"."C#PROT_N" IS 'номер протокола';
   COMMENT ON COLUMN "FCR"."T#B_ACCOUNT"."C#PROT_DATE" IS 'дата протокола';
