--------------------------------------------------------
--  Constraints for Table T#B_OP
--------------------------------------------------------

  ALTER TABLE "FCR"."T#B_OP" MODIFY ("C#OPS_ID" NOT NULL ENABLE);
  ALTER TABLE "FCR"."T#B_OP" MODIFY ("C#HOUSE_ID" NOT NULL ENABLE);
  ALTER TABLE "FCR"."T#B_OP" MODIFY ("C#SERVICE_ID" NOT NULL ENABLE);
  ALTER TABLE "FCR"."T#B_OP" MODIFY ("C#B_ACCOUNT_ID" NOT NULL ENABLE);
  ALTER TABLE "FCR"."T#B_OP" MODIFY ("C#DATE" NOT NULL ENABLE);
  ALTER TABLE "FCR"."T#B_OP" MODIFY ("C#TYPE_TAG" NOT NULL ENABLE);
  ALTER TABLE "FCR"."T#B_OP" ADD CONSTRAINT "CC#B_OP#TT" CHECK (C#TYPE_TAG in ('M','P','T')) ENABLE;
  ALTER TABLE "FCR"."T#B_OP" ADD CONSTRAINT "CP#B_OP" PRIMARY KEY ("C#ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS#DATA1"  ENABLE;
