--------------------------------------------------------
--  DDL for Table T#B_STORAGE
--------------------------------------------------------

  CREATE TABLE "FCR"."T#B_STORAGE" 
   (	"C#HOUSE_ID" NUMBER(*,0), 
	"C#SERVICE_ID" NUMBER(*,0), 
	"C#B_ACCOUNT_ID" NUMBER(*,0), 
	"C#MN" NUMBER(4,0), 
	"C#C_SUM" NUMBER(38,2), 
	"C#M_SUM" NUMBER(38,2), 
	"C#P_SUM" NUMBER(38,2), 
	"C#T_SUM" NUMBER(38,2)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS#DATA1" ;

   COMMENT ON COLUMN "FCR"."T#B_STORAGE"."C#C_SUM" IS 'Сумма начислений (сборов).';
   COMMENT ON COLUMN "FCR"."T#B_STORAGE"."C#M_SUM" IS 'Сумма изменений.';
   COMMENT ON COLUMN "FCR"."T#B_STORAGE"."C#P_SUM" IS 'Сумма платежей (погашений).';
   COMMENT ON COLUMN "FCR"."T#B_STORAGE"."C#T_SUM" IS 'Сумма трасферов.';
