--------------------------------------------------------
--  Constraints for Table T#B_OBJ
--------------------------------------------------------

  ALTER TABLE "FCR"."T#B_OBJ" ADD CONSTRAINT "CP#B_OBJ" PRIMARY KEY ("C#HOUSE_ID", "C#SERVICE_ID", "C#B_ACCOUNT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS#DATA1"  ENABLE;
