--------------------------------------------------------
--  Constraints for Table T#B_ACCOUNT
--------------------------------------------------------

  ALTER TABLE "FCR"."T#B_ACCOUNT" ADD CONSTRAINT "CC#B_ACCOUNT#NUM" CHECK (regexp_like(C#NUM,'^[0-9]{20}$')) ENABLE;
  ALTER TABLE "FCR"."T#B_ACCOUNT" ADD CONSTRAINT "CC#B_ACCOUNT#INN" CHECK (regexp_like(C#INN_NUM,'^[0-9]{10}([0-9]{2})?$')) ENABLE;
  ALTER TABLE "FCR"."T#B_ACCOUNT" ADD CONSTRAINT "CC#B_ACCOUNT#AT" CHECK (C#ACC_TYPE in (1,2,50)) ENABLE;
  ALTER TABLE "FCR"."T#B_ACCOUNT" ADD CONSTRAINT "CC#B_ACCOUNT#KPP" CHECK (regexp_like(C#KPP_NUM,'^[0-9]{9}$')) ENABLE;
  ALTER TABLE "FCR"."T#B_ACCOUNT" MODIFY ("C#BANK_ID" NOT NULL ENABLE);
  ALTER TABLE "FCR"."T#B_ACCOUNT" MODIFY ("C#NUM" NOT NULL ENABLE);
  ALTER TABLE "FCR"."T#B_ACCOUNT" ADD CONSTRAINT "CP#B_ACCOUNT" PRIMARY KEY ("C#ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS#DATA1"  ENABLE;
  ALTER TABLE "FCR"."T#B_ACCOUNT" ADD CONSTRAINT "CU#B_ACCOUNT#1" UNIQUE ("C#BANK_ID", "C#NUM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS#DATA1"  ENABLE;
