--------------------------------------------------------
--  DDL for Table T#BANK_ALL
--------------------------------------------------------

  CREATE TABLE "FCR"."T#BANK_ALL" 
   (	"VKEY" VARCHAR2(8 BYTE), 
	"REAL" VARCHAR2(4 BYTE), 
	"PZN" VARCHAR2(2 BYTE), 
	"UER" VARCHAR2(1 BYTE), 
	"RGN" VARCHAR2(2 BYTE), 
	"IND" VARCHAR2(6 BYTE), 
	"TNP" VARCHAR2(1 BYTE), 
	"NNP" VARCHAR2(25 BYTE), 
	"ADR" VARCHAR2(30 BYTE), 
	"RKC" VARCHAR2(9 BYTE), 
	"NAMEP" VARCHAR2(45 BYTE), 
	"NAMEN" VARCHAR2(30 BYTE), 
	"NEWNUM" VARCHAR2(9 BYTE), 
	"NEWKS" VARCHAR2(9 BYTE), 
	"PERMFO" VARCHAR2(6 BYTE), 
	"SROK" VARCHAR2(2 BYTE), 
	"AT1" VARCHAR2(6 BYTE), 
	"AT2" VARCHAR2(6 BYTE), 
	"TELEF" VARCHAR2(25 BYTE), 
	"REGN" VARCHAR2(9 BYTE), 
	"OKPO" VARCHAR2(8 BYTE), 
	"DT_IZM" DATE, 
	"CKS" VARCHAR2(6 BYTE), 
	"KSNP" VARCHAR2(20 BYTE), 
	"DATE_IN" DATE, 
	"DATE_CH" DATE, 
	"VKEYDEL" VARCHAR2(8 BYTE), 
	"DT_IZMR" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS#DATA1" ;
