--------------------------------------------------------
--  DDL for Table T#BANK
--------------------------------------------------------

  CREATE TABLE "FCR"."T#BANK" 
   (	"C#ID" NUMBER(*,0), 
	"C#NAME" VARCHAR2(50 BYTE), 
	"C#BIC_NUM" VARCHAR2(9 BYTE), 
	"C#CA_NUM" VARCHAR2(20 BYTE), 
	"C#TOWN_NAME" VARCHAR2(30 BYTE), 
	"C#KPP" VARCHAR2(20 BYTE), 
	"C#OGRN" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS#DATA1" ;

   COMMENT ON COLUMN "FCR"."T#BANK"."C#NAME" IS 'Наименование.';
   COMMENT ON COLUMN "FCR"."T#BANK"."C#BIC_NUM" IS 'БИК.';
   COMMENT ON COLUMN "FCR"."T#BANK"."C#CA_NUM" IS 'Корр. счёт.';
   COMMENT ON COLUMN "FCR"."T#BANK"."C#TOWN_NAME" IS 'Город, бля.';
