--------------------------------------------------------
--  Constraints for Table T#CHARGE
--------------------------------------------------------

  ALTER TABLE "FCR"."T#CHARGE" MODIFY ("C#ACCOUNT_ID" NOT NULL ENABLE);
  ALTER TABLE "FCR"."T#CHARGE" MODIFY ("C#WORK_ID" NOT NULL ENABLE);
  ALTER TABLE "FCR"."T#CHARGE" MODIFY ("C#DOER_ID" NOT NULL ENABLE);
  ALTER TABLE "FCR"."T#CHARGE" MODIFY ("C#MN" NOT NULL ENABLE);
  ALTER TABLE "FCR"."T#CHARGE" MODIFY ("C#A_MN" NOT NULL ENABLE);
  ALTER TABLE "FCR"."T#CHARGE" MODIFY ("C#B_MN" NOT NULL ENABLE);
  ALTER TABLE "FCR"."T#CHARGE" MODIFY ("C#VOL" NOT NULL ENABLE);
  ALTER TABLE "FCR"."T#CHARGE" MODIFY ("C#SUM" NOT NULL ENABLE);
  ALTER TABLE "FCR"."T#CHARGE" MODIFY ("C#SIGN_DATE" NOT NULL ENABLE);
  ALTER TABLE "FCR"."T#CHARGE" MODIFY ("C#SIGN_S_ID" NOT NULL ENABLE);
  ALTER TABLE "FCR"."T#CHARGE" ADD CONSTRAINT "CP#CHARGE" PRIMARY KEY ("C#ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS#DATA1"  ENABLE;
  ALTER TABLE "FCR"."T#CHARGE" ADD CONSTRAINT "CU#CHARGE" UNIQUE ("C#ACCOUNT_ID", "C#WORK_ID", "C#DOER_ID", "C#MN", "C#A_MN", "C#B_MN")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS#DATA1"  ENABLE;
