--------------------------------------------------------
--  DDL for Table T_CLAIM
--------------------------------------------------------

  CREATE TABLE "FCR"."T_CLAIM" 
   (	"C_ID" NUMBER(10,0), 
	"C_NUMBER" NUMBER, 
	"C_DATE" DATE, 
	"C_COMMENT" VARCHAR2(255 BYTE), 
	"C_SUMMA_CLAIM" FLOAT(40), 
	"C_SUMMA_DUTY" FLOAT(40), 
	"T_TYPE_CLAIMC_ID" NUMBER(10,0), 
	"C_PREFIX" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS#DATA1" ;

   COMMENT ON COLUMN "FCR"."T_CLAIM"."C_ID" IS 'Ид. иска';
   COMMENT ON COLUMN "FCR"."T_CLAIM"."C_NUMBER" IS 'Номер иска';
   COMMENT ON COLUMN "FCR"."T_CLAIM"."C_DATE" IS 'Дата иска';
   COMMENT ON COLUMN "FCR"."T_CLAIM"."C_COMMENT" IS 'Комментарий
';
   COMMENT ON COLUMN "FCR"."T_CLAIM"."C_SUMMA_CLAIM" IS 'Сумма иска
';
   COMMENT ON COLUMN "FCR"."T_CLAIM"."C_SUMMA_DUTY" IS 'Сумма госпошлины';
   COMMENT ON COLUMN "FCR"."T_CLAIM"."T_TYPE_CLAIMC_ID" IS 'Ид. типа иска';
   COMMENT ON COLUMN "FCR"."T_CLAIM"."C_PREFIX" IS 'Префикс номера';
