--------------------------------------------------------
--  Constraints for Table T#CLOSE
--------------------------------------------------------

  ALTER TABLE "FCR"."T#CLOSE" MODIFY ("C#HOUSE_ID" NOT NULL ENABLE);
  ALTER TABLE "FCR"."T#CLOSE" MODIFY ("C#SERVICE_ID" NOT NULL ENABLE);
  ALTER TABLE "FCR"."T#CLOSE" ADD CONSTRAINT "CP#CLOSE" PRIMARY KEY ("C#ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS#DATA1"  ENABLE;
  ALTER TABLE "FCR"."T#CLOSE" ADD CONSTRAINT "CU#CLOSE" UNIQUE ("C#HOUSE_ID", "C#SERVICE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS#DATA1"  ENABLE;
