--------------------------------------------------------
--  DDL for Table T#CLOSE_VD
--------------------------------------------------------

  CREATE TABLE "FCR"."T#CLOSE_VD" 
   (	"C#ID" NUMBER(*,0), 
	"C#VN" NUMBER(*,0), 
	"C#VALID_TAG" VARCHAR2(1 BYTE), 
	"C#SIGN_DATE" DATE, 
	"C#SIGN_S_ID" NUMBER, 
	"C#MN" NUMBER(4,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 8192 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS#DATA1" ;

   COMMENT ON COLUMN "FCR"."T#CLOSE_VD"."C#VN" IS 'Номер версии.';
   COMMENT ON COLUMN "FCR"."T#CLOSE_VD"."C#VALID_TAG" IS 'Действующая {"N":нет;"Y":да}.';
   COMMENT ON COLUMN "FCR"."T#CLOSE_VD"."C#SIGN_DATE" IS 'Подпись, дата.';
   COMMENT ON COLUMN "FCR"."T#CLOSE_VD"."C#SIGN_S_ID" IS 'Подпись, ид сессии.';
   COMMENT ON COLUMN "FCR"."T#CLOSE_VD"."C#MN" IS 'Начало открытого периода.';
