--------------------------------------------------------
--  DDL for Index T_COURT_C_ID_IDX
--------------------------------------------------------

  CREATE UNIQUE INDEX "FCR"."T_COURT_C_ID_IDX" ON "FCR"."T_COURT" ("C_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS#DATA1" ;
