--------------------------------------------------------
--  Constraints for Table T_COURT
--------------------------------------------------------

  ALTER TABLE "FCR"."T_COURT" MODIFY ("T_TYPE_C_ID" NOT NULL ENABLE);
  ALTER TABLE "FCR"."T_COURT" MODIFY ("T_ADDRESS_C_ID" CONSTRAINT "NNC_T_COURT_T_ADDRESS_C_ID" NOT NULL ENABLE);
  ALTER TABLE "FCR"."T_COURT" ADD CONSTRAINT "T_COURT_PK" PRIMARY KEY ("C_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS#DATA1"  ENABLE;
  ALTER TABLE "FCR"."T_COURT" MODIFY ("C_ID" NOT NULL ENABLE);
