--------------------------------------------------------
--  Constraints for Table T#CUSTOM_TOOLS
--------------------------------------------------------

  ALTER TABLE "FCR"."T#CUSTOM_TOOLS" MODIFY ("C#TITLE" NOT NULL ENABLE);
  ALTER TABLE "FCR"."T#CUSTOM_TOOLS" MODIFY ("C#TEXT" NOT NULL ENABLE);
  ALTER TABLE "FCR"."T#CUSTOM_TOOLS" MODIFY ("C#ID" NOT NULL ENABLE);
  ALTER TABLE "FCR"."T#CUSTOM_TOOLS" ADD CONSTRAINT "T#CUSTOM_TOOLS_PK" PRIMARY KEY ("C#ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS#DATA1"  ENABLE;
