--------------------------------------------------------
--  Constraints for Table T_DATA_DEFENDANT
--------------------------------------------------------

  ALTER TABLE "FCR"."T_DATA_DEFENDANT" MODIFY ("C_ID_DEF" NOT NULL ENABLE);
  ALTER TABLE "FCR"."T_DATA_DEFENDANT" ADD CONSTRAINT "T_DATA_DEFENDANT_PK" PRIMARY KEY ("C_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "TS#DATA1"  ENABLE;
  ALTER TABLE "FCR"."T_DATA_DEFENDANT" MODIFY ("C_ID" NOT NULL ENABLE);
