--------------------------------------------------------
--  Constraints for Table T_DEF_ROOMS
--------------------------------------------------------

  ALTER TABLE "FCR"."T_DEF_ROOMS" MODIFY ("C_ID_DEF" NOT NULL ENABLE);
  ALTER TABLE "FCR"."T_DEF_ROOMS" MODIFY ("C_ROOMS_ID" NOT NULL ENABLE);
  ALTER TABLE "FCR"."T_DEF_ROOMS" ADD CONSTRAINT "T_DEF_ROOMS_PK" PRIMARY KEY ("C_ROOMS_ID", "C_ID_DEF")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS#DATA1"  ENABLE;
