--------------------------------------------------------
--  DDL for Table T_DEF_ROOMS
--------------------------------------------------------

  CREATE TABLE "FCR"."T_DEF_ROOMS" 
   (	"C_ID_DEF" NUMBER(10,0), 
	"C_ROOMS_ID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS#DATA1" ;

   COMMENT ON COLUMN "FCR"."T_DEF_ROOMS"."C_ID_DEF" IS 'Сcылка на владельца
';
   COMMENT ON COLUMN "FCR"."T_DEF_ROOMS"."C_ROOMS_ID" IS 'Ид помещения';
