--------------------------------------------------------
--  DDL for Table T_DOC_DEFENDANT
--------------------------------------------------------

  CREATE TABLE "FCR"."T_DOC_DEFENDANT" 
   (	"C_ID" NUMBER(10,0), 
	"T_TYPE_DOCC_ID" NUMBER(10,0), 
	"C_SERIES" VARCHAR2(20 BYTE), 
	"C_NUMBER" VARCHAR2(20 BYTE), 
	"C_GIVE" VARCHAR2(255 BYTE), 
	"C_DATE" DATE, 
	"C_ADDITIONAL" VARCHAR2(255 BYTE), 
	"C_COMMENT" VARCHAR2(255 BYTE), 
	"C_ID_DEF" NUMBER
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "TS#DATA1" ;

   COMMENT ON COLUMN "FCR"."T_DOC_DEFENDANT"."C_ID_DEF" IS 'Ид ответчика';
