--------------------------------------------------------
--  DDL for Table T#ERC_NACH
--------------------------------------------------------

  CREATE TABLE "FCR"."T#ERC_NACH" 
   (	"PER" VARCHAR2(20 BYTE), 
	"HOST" VARCHAR2(100 BYTE), 
	"CITY" VARCHAR2(100 BYTE), 
	"UL_NAME" VARCHAR2(100 BYTE), 
	"DOM" VARCHAR2(100 BYTE), 
	"DOP_NAME" VARCHAR2(100 BYTE), 
	"KV" VARCHAR2(100 BYTE), 
	"LSO" VARCHAR2(50 BYTE), 
	"PL_OB" NUMBER(*,1), 
	"KAPREM_RASC" NUMBER(*,2), 
	"NA_KAPREM" NUMBER(*,2), 
	"IKS_KAPREM" NUMBER(*,2)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS#DATA1" ;
