--------------------------------------------------------
--  Constraints for Table T#ERC_NACH
--------------------------------------------------------

  ALTER TABLE "FCR"."T#ERC_NACH" ADD CONSTRAINT "T#ERC_NACH_UK1" UNIQUE ("PER", "LSO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS#DATA1"  ENABLE;
