--------------------------------------------------------
--  DDL for Table T#EXCEPTION
--------------------------------------------------------

  CREATE TABLE "FCR"."T#EXCEPTION" 
   (	"C#NAME_PACKAGE" VARCHAR2(250 BYTE), 
	"C#NAME_PROC" VARCHAR2(250 BYTE), 
	"C#DATE" DATE, 
	"C#TEXT" VARCHAR2(4000 BYTE), 
	"C#COMMENT" VARCHAR2(4000 BYTE), 
	"C#USER" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS#DATA1" ;

   COMMENT ON COLUMN "FCR"."T#EXCEPTION"."C#NAME_PACKAGE" IS 'пакет';
   COMMENT ON COLUMN "FCR"."T#EXCEPTION"."C#NAME_PROC" IS 'процедура';
   COMMENT ON COLUMN "FCR"."T#EXCEPTION"."C#DATE" IS 'дата';
   COMMENT ON COLUMN "FCR"."T#EXCEPTION"."C#TEXT" IS 'текст';
   COMMENT ON COLUMN "FCR"."T#EXCEPTION"."C#COMMENT" IS 'дополнительные данные';
