--------------------------------------------------------
--  Constraints for Table T#FCR_DBF
--------------------------------------------------------

  ALTER TABLE "FCR"."T#FCR_DBF" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "FCR"."T#FCR_DBF" ADD CONSTRAINT "T#FCR_DBF_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS#DATA1"  ENABLE;
