--------------------------------------------------------
--  DDL for Table T#FILE_PAY
--------------------------------------------------------

  CREATE TABLE "FCR"."T#FILE_PAY" 
   (	"C#ID" NUMBER(*,0), 
	"C#DESC" VARCHAR2(100 BYTE), 
	"C#F_NUM" VARCHAR2(250 BYTE), 
	"C#PATH" VARCHAR2(250 BYTE), 
	"C#ROW_TIME" TIMESTAMP (6) DEFAULT sysdate
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 8192 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS#DATA1" ;
