--------------------------------------------------------
--  DDL for Table T#GIS_ACCLIST_FROM_GIS
--------------------------------------------------------

  CREATE TABLE "FCR"."T#GIS_ACCLIST_FROM_GIS" 
   (	"ACCOUNT_NUM" VARCHAR2(50 BYTE), 
	"ED_LIC_ACC" VARCHAR2(50 BYTE), 
	"GKU_ID" VARCHAR2(50 BYTE), 
	"POM_GIS_GUID" VARCHAR2(50 BYTE), 
	"ADDR" VARCHAR2(500 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS#DATA1" ;
