--------------------------------------------------------
--  DDL for Table T#HOUSE
--------------------------------------------------------

  CREATE TABLE "FCR"."T#HOUSE" 
   (	"C#ID" NUMBER(*,0), 
	"C#ADDR_OBJ_ID" NUMBER(*,0), 
	"C#NUM" VARCHAR2(20 BYTE), 
	"C#B_NUM" VARCHAR2(10 BYTE), 
	"C#S_NUM" VARCHAR2(10 BYTE), 
	"C#POST_CODE" VARCHAR2(6 BYTE), 
	"C#FIAS_GUID" VARCHAR2(36 BYTE), 
	"C#ID_HOUSE" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 8192 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS#DATA1" ;

   COMMENT ON COLUMN "FCR"."T#HOUSE"."C#NUM" IS 'номер дома';
