--------------------------------------------------------
--  Constraints for Table T#HOUSE_WALL_TYPE
--------------------------------------------------------

  ALTER TABLE "FCR"."T#HOUSE_WALL_TYPE" MODIFY ("C#NAME" NOT NULL ENABLE);
  ALTER TABLE "FCR"."T#HOUSE_WALL_TYPE" ADD CONSTRAINT "CP#HOUSE_WALL_TYPE" PRIMARY KEY ("C#ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS#DATA1"  ENABLE;
  ALTER TABLE "FCR"."T#HOUSE_WALL_TYPE" ADD CONSTRAINT "CU#HOUSE_WALL_TYPE" UNIQUE ("C#NAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS#DATA1"  ENABLE;
