--------------------------------------------------------
--  DDL for Table T#HOUSE_INFO_OLDVERSION
--------------------------------------------------------

  CREATE TABLE "FCR"."T#HOUSE_INFO_OLDVERSION" 
   (	"C#HOUSE_ID" NUMBER(*,0), 
	"C#PROG_NUM" NUMBER(5,0), 
	"C#GU_ID" NUMBER(7,0), 
	"C#1ST_DATE" DATE, 
	"C#2ND_DATE" DATE, 
	"C#END_DATE" DATE, 
	"C#AREA_VAL" NUMBER, 
	"C#FLOOR_CNT" NUMBER, 
	"C#ELEVATOR_TAG" VARCHAR2(1 BYTE), 
	"C#BASEMENT_TAG" VARCHAR2(1 BYTE), 
	"C#WALL_TYPE_ID" NUMBER(*,0), 
	"C#CREATE_YEAR" NUMBER(4,0), 
	"C#ROOF_L_YEAR" NUMBER(4,0), 
	"C#ROOF_H_YEAR" NUMBER(4,0), 
	"C#FACE_L_YEAR" NUMBER(4,0), 
	"C#FACE_H_YEAR" NUMBER(4,0), 
	"C#ISYS_L_YEAR" NUMBER(4,0), 
	"C#ISYS_H_YEAR" NUMBER(4,0), 
	"C#CMET_L_YEAR" NUMBER(4,0), 
	"C#CMET_H_YEAR" NUMBER(4,0), 
	"C#ELEV_L_YEAR" NUMBER(4,0), 
	"C#ELEV_H_YEAR" NUMBER(4,0), 
	"C#BASE_L_YEAR" NUMBER(4,0), 
	"C#BASE_H_YEAR" NUMBER(4,0), 
	"C#FUND_L_YEAR" NUMBER(4,0), 
	"C#FUND_H_YEAR" NUMBER(4,0), 
	"C#VOTE_DATE" DATE, 
	"C#VOTE_TEXT" VARCHAR2(200 BYTE), 
	"C#ORG_NAME" VARCHAR2(100 BYTE), 
	"C#GOV_NAME" VARCHAR2(100 BYTE), 
	"C#OMSU_ID" VARCHAR2(20 BYTE), 
	"C#LIVE_AREA_VAL" NUMBER, 
	"C#FLORS" NUMBER, 
	"C#ELEV_COL" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS#DATA1" ;

   COMMENT ON COLUMN "FCR"."T#HOUSE_INFO_OLDVERSION"."C#PROG_NUM" IS 'Номер в программе.';
   COMMENT ON COLUMN "FCR"."T#HOUSE_INFO_OLDVERSION"."C#GU_ID" IS 'Ид в госуслугах.';
   COMMENT ON COLUMN "FCR"."T#HOUSE_INFO_OLDVERSION"."C#1ST_DATE" IS 'Дата начала программы.';
   COMMENT ON COLUMN "FCR"."T#HOUSE_INFO_OLDVERSION"."C#2ND_DATE" IS 'Дата начала начислений.';
   COMMENT ON COLUMN "FCR"."T#HOUSE_INFO_OLDVERSION"."C#END_DATE" IS 'Дата конца.';
   COMMENT ON COLUMN "FCR"."T#HOUSE_INFO_OLDVERSION"."C#AREA_VAL" IS 'Значение площади (общей).';
   COMMENT ON COLUMN "FCR"."T#HOUSE_INFO_OLDVERSION"."C#FLOOR_CNT" IS 'Количество этажей.';
   COMMENT ON COLUMN "FCR"."T#HOUSE_INFO_OLDVERSION"."C#ELEVATOR_TAG" IS 'Лифт (наличие).';
   COMMENT ON COLUMN "FCR"."T#HOUSE_INFO_OLDVERSION"."C#BASEMENT_TAG" IS 'Подвал (наличие).';
   COMMENT ON COLUMN "FCR"."T#HOUSE_INFO_OLDVERSION"."C#WALL_TYPE_ID" IS 'Ид типа (материала) стен.';
   COMMENT ON COLUMN "FCR"."T#HOUSE_INFO_OLDVERSION"."C#CREATE_YEAR" IS 'Год создания (постройки).';
   COMMENT ON COLUMN "FCR"."T#HOUSE_INFO_OLDVERSION"."C#ROOF_L_YEAR" IS 'Нижний год ремонта крыши.';
   COMMENT ON COLUMN "FCR"."T#HOUSE_INFO_OLDVERSION"."C#ROOF_H_YEAR" IS 'Верхний год ремонта крыши.';
   COMMENT ON COLUMN "FCR"."T#HOUSE_INFO_OLDVERSION"."C#FACE_L_YEAR" IS 'Нижний год ремонта фасада.';
   COMMENT ON COLUMN "FCR"."T#HOUSE_INFO_OLDVERSION"."C#FACE_H_YEAR" IS 'Верхний год ремонта фасада.';
   COMMENT ON COLUMN "FCR"."T#HOUSE_INFO_OLDVERSION"."C#ISYS_L_YEAR" IS 'Нижний год ремонта инженерных систем.';
   COMMENT ON COLUMN "FCR"."T#HOUSE_INFO_OLDVERSION"."C#ISYS_H_YEAR" IS 'Верхний год ремонта инженерных систем.';
   COMMENT ON COLUMN "FCR"."T#HOUSE_INFO_OLDVERSION"."C#CMET_L_YEAR" IS 'Нижний год замены ОПУ.';
   COMMENT ON COLUMN "FCR"."T#HOUSE_INFO_OLDVERSION"."C#CMET_H_YEAR" IS 'Верхний год замены ОПУ.';
   COMMENT ON COLUMN "FCR"."T#HOUSE_INFO_OLDVERSION"."C#ELEV_L_YEAR" IS 'Нижний год ремонта лифта.';
   COMMENT ON COLUMN "FCR"."T#HOUSE_INFO_OLDVERSION"."C#ELEV_H_YEAR" IS 'Верхний год ремонта лифта.';
   COMMENT ON COLUMN "FCR"."T#HOUSE_INFO_OLDVERSION"."C#BASE_L_YEAR" IS 'Нижний год ремонта подвала.';
   COMMENT ON COLUMN "FCR"."T#HOUSE_INFO_OLDVERSION"."C#BASE_H_YEAR" IS 'Верхний год ремонта подвала.';
   COMMENT ON COLUMN "FCR"."T#HOUSE_INFO_OLDVERSION"."C#FUND_L_YEAR" IS 'Нижний год ремонта фундамента.';
   COMMENT ON COLUMN "FCR"."T#HOUSE_INFO_OLDVERSION"."C#FUND_H_YEAR" IS 'Верхний год ремонта фундамента.';
   COMMENT ON COLUMN "FCR"."T#HOUSE_INFO_OLDVERSION"."C#VOTE_DATE" IS 'Дата голосования (постановления).';
   COMMENT ON COLUMN "FCR"."T#HOUSE_INFO_OLDVERSION"."C#VOTE_TEXT" IS 'Текст голосования (постановления).';
   COMMENT ON COLUMN "FCR"."T#HOUSE_INFO_OLDVERSION"."C#ORG_NAME" IS 'Наименование организации (управляющей).';
   COMMENT ON COLUMN "FCR"."T#HOUSE_INFO_OLDVERSION"."C#GOV_NAME" IS 'Наименование органа (управления).';
   COMMENT ON COLUMN "FCR"."T#HOUSE_INFO_OLDVERSION"."C#OMSU_ID" IS 'Муниципальное образование';
   COMMENT ON COLUMN "FCR"."T#HOUSE_INFO_OLDVERSION"."C#LIVE_AREA_VAL" IS 'Жилая площадь';
   COMMENT ON COLUMN "FCR"."T#HOUSE_INFO_OLDVERSION"."C#FLORS" IS 'Количество этажей';
   COMMENT ON COLUMN "FCR"."T#HOUSE_INFO_OLDVERSION"."C#ELEV_COL" IS 'Количество лифтов';
