--------------------------------------------------------
--  Constraints for Table T#HOUSE
--------------------------------------------------------

  ALTER TABLE "FCR"."T#HOUSE" ADD CONSTRAINT "CC#HOUSE#FG" CHECK (regexp_like(C#FIAS_GUID,'^[0-9a-f]{8}-([0-9a-f]{4}-){3}[0-9a-f]{12}$')) ENABLE;
  ALTER TABLE "FCR"."T#HOUSE" ADD CONSTRAINT "CC#HOUSE#PC" CHECK (regexp_like(C#POST_CODE,'^[0-9]{6}$')) DISABLE;
  ALTER TABLE "FCR"."T#HOUSE" ADD CONSTRAINT "CU#HOUSE#1" UNIQUE ("C#ADDR_OBJ_ID", "C#NUM", "C#B_NUM", "C#S_NUM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS#DATA1"  ENABLE;
  ALTER TABLE "FCR"."T#HOUSE" MODIFY ("C#ADDR_OBJ_ID" NOT NULL ENABLE);
  ALTER TABLE "FCR"."T#HOUSE" MODIFY ("C#NUM" NOT NULL ENABLE);
  ALTER TABLE "FCR"."T#HOUSE" ADD CONSTRAINT "CP#HOUSE" PRIMARY KEY ("C#ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS#DATA1"  ENABLE;
