--------------------------------------------------------
--  DDL for Table T#HOUSE_INFO_EXCEL
--------------------------------------------------------

  CREATE TABLE "FCR"."T#HOUSE_INFO_EXCEL" 
   (	"C#HOUSE_ID" NUMBER(*,0), 
	"C#PROG_NUM" NUMBER(5,0), 
	"C#GU_ID" NUMBER(7,0), 
	"C#1ST_DATE" DATE, 
	"C#2ND_DATE" DATE, 
	"C#END_DATE" DATE, 
	"C#AREA_VAL" NUMBER, 
	"C#FLOOR_CNT" NUMBER, 
	"C#ELEVATOR_TAG" VARCHAR2(1 BYTE), 
	"C#BASEMENT_TAG" VARCHAR2(1 BYTE), 
	"C#WALL_TYPE_ID" NUMBER(*,0), 
	"C#CREATE_YEAR" NUMBER(4,0), 
	"C#ROOF_L_YEAR" NUMBER(4,0), 
	"C#ROOF_H_YEAR" NUMBER(4,0), 
	"C#FACE_L_YEAR" NUMBER(4,0), 
	"C#FACE_H_YEAR" NUMBER(4,0), 
	"C#ISYS_L_YEAR" NUMBER(4,0), 
	"C#ISYS_H_YEAR" NUMBER(4,0), 
	"C#CMET_L_YEAR" NUMBER(4,0), 
	"C#CMET_H_YEAR" NUMBER(4,0), 
	"C#ELEV_L_YEAR" NUMBER(4,0), 
	"C#ELEV_H_YEAR" NUMBER(4,0), 
	"C#BASE_L_YEAR" NUMBER(4,0), 
	"C#BASE_H_YEAR" NUMBER(4,0), 
	"C#FUND_L_YEAR" NUMBER(4,0), 
	"C#FUND_H_YEAR" NUMBER(4,0), 
	"C#VOTE_DATE" DATE, 
	"C#VOTE_TEXT" VARCHAR2(200 BYTE), 
	"C#ORG_NAME" VARCHAR2(100 BYTE), 
	"C#GOV_NAME" VARCHAR2(100 BYTE), 
	"C#OMSU_ID" VARCHAR2(20 BYTE), 
	"C#LIVE_AREA_VAL" NUMBER, 
	"C#FLORS" VARCHAR2(20 BYTE), 
	"C#ELEV_COL" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS#DATA1" ;
