--------------------------------------------------------
--  DDL for Table T#LOG
--------------------------------------------------------

  CREATE TABLE "FCR"."T#LOG" 
   (	"C#ID" NUMBER(10,0), 
	"C#DATE" DATE, 
	"C#ADR" VARCHAR2(300 CHAR), 
	"C#LS" VARCHAR2(50 CHAR), 
	"C#OWNER" VARCHAR2(200 CHAR), 
	"C#TYPE_READ" VARCHAR2(50 CHAR), 
	"C#ID_SOURSE" VARCHAR2(50 CHAR), 
	"C#NOTE" VARCHAR2(400 CHAR), 
	"C#AUTHOR" VARCHAR2(50 CHAR), 
	"C#TP_FLAG" VARCHAR2(50 CHAR), 
	"C#OLD_RECORD" VARCHAR2(100 BYTE), 
	"C#NEW_RECORD" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS#DATA1" ;
