--------------------------------------------------------
--  DDL for Table T#MASS_PAY_BACK
--------------------------------------------------------

  CREATE TABLE "FCR"."T#MASS_PAY_BACK" 
   (	"C#ID" VARCHAR2(26 BYTE), 
	"C#PERSON_ID" NUMBER(*,0), 
	"C#SUM" NUMBER(26,0), 
	"C#DATE" DATE, 
	"C#LIVING_TAG" VARCHAR2(26 BYTE), 
	"C#OPS_ID" NUMBER(*,0), 
	"C#PARENT_ID" NUMBER(*,0), 
	"C#NPD" VARCHAR2(26 BYTE), 
	"C#COD_RKC" NUMBER(*,0), 
	"C#COMMENT" VARCHAR2(256 BYTE), 
	"C#REMOVE_FLG" VARCHAR2(26 BYTE), 
	"C#ACC_ID" VARCHAR2(26 BYTE), 
	"C#STORNO_FLG" VARCHAR2(26 BYTE), 
	"Ñ#OSTATOK" NUMBER(26,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS#DATA1" ;
