--------------------------------------------------------
--  DDL for Table T#MUPERC2108
--------------------------------------------------------

  CREATE TABLE "FCR"."T#MUPERC2108" 
   (	"LSO" VARCHAR2(12 BYTE), 
	"C$YM" VARCHAR2(8 BYTE), 
	"REM" VARCHAR2(12 BYTE), 
	"C#ACCOUNT_ID" NUMBER(38,0), 
	"C#ACCOUNT_NEW" NUMBER(38,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS#DATA1" ;
