--------------------------------------------------------
--  DDL for Table T#MUPERC
--------------------------------------------------------

  CREATE TABLE "FCR"."T#MUPERC" 
   (	"LSO" VARCHAR2(20 BYTE), 
	"HOST" VARCHAR2(26 BYTE), 
	"CITY" VARCHAR2(26 BYTE), 
	"UL_NAME" VARCHAR2(250 BYTE), 
	"DOM" VARCHAR2(26 BYTE), 
	"DOP_NAME" VARCHAR2(50 BYTE), 
	"KV" VARCHAR2(26 BYTE), 
	"PL_OB" NUMBER(6,2), 
	"UL" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS#DATA1" ;
