--------------------------------------------------------
--  DDL for Table T#OBJ
--------------------------------------------------------

  CREATE TABLE "FCR"."T#OBJ" 
   (	"C#ACCOUNT_ID" NUMBER(*,0), 
	"C#WORK_ID" NUMBER(*,0), 
	"C#DOER_ID" NUMBER(*,0), 
	 CONSTRAINT "CP#OBJ" PRIMARY KEY ("C#ACCOUNT_ID", "C#WORK_ID", "C#DOER_ID") ENABLE
   ) ORGANIZATION INDEX NOCOMPRESS PCTFREE 10 INITRANS 2 MAXTRANS 255 LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS#DATA1" 
 PCTTHRESHOLD 50;
