--------------------------------------------------------
--  DDL for Table T#OMSU_VD
--------------------------------------------------------

  CREATE TABLE "FCR"."T#OMSU_VD" 
   (	"C#ID" NUMBER(38,0), 
	"C#VN" NUMBER(38,0) DEFAULT 1, 
	"C#VALID_TAG" VARCHAR2(1 BYTE) DEFAULT 'Y', 
	"C#SIGN_DATE" DATE DEFAULT sysdate, 
	"C#SIGN_S_ID" NUMBER(38,0), 
	"C#NAME_MO" VARCHAR2(250 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS#DATA1" ;

   COMMENT ON COLUMN "FCR"."T#OMSU_VD"."C#ID" IS 'Ид.Хоста
';
   COMMENT ON COLUMN "FCR"."T#OMSU_VD"."C#VN" IS 'Версия
';
   COMMENT ON COLUMN "FCR"."T#OMSU_VD"."C#VALID_TAG" IS 'Действующая {"N":нет;"Y":да}.';
   COMMENT ON COLUMN "FCR"."T#OMSU_VD"."C#SIGN_DATE" IS 'Подпись, дата.';
   COMMENT ON COLUMN "FCR"."T#OMSU_VD"."C#SIGN_S_ID" IS 'Подпись, ид сессии.';
