--------------------------------------------------------
--  DDL for Table T#ONLINE_KVIT
--------------------------------------------------------

  CREATE TABLE "FCR"."T#ONLINE_KVIT" 
   (	"ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE , 
	"ACC_NUM" VARCHAR2(50 BYTE), 
	"PERIOD" VARCHAR2(7 BYTE), 
	"KVIT" VARCHAR2(1 BYTE), 
	"ROW_TIME" TIMESTAMP (6) DEFAULT systimestamp
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS#DATA1" ;
  GRANT INSERT ON "FCR"."T#ONLINE_KVIT" TO "FCR_READ_ONLY";
