--------------------------------------------------------
--  Constraints for Table T#ONLINE_KVIT
--------------------------------------------------------

  ALTER TABLE "FCR"."T#ONLINE_KVIT" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "FCR"."T#ONLINE_KVIT" MODIFY ("ACC_NUM" NOT NULL ENABLE);
  ALTER TABLE "FCR"."T#ONLINE_KVIT" MODIFY ("PERIOD" NOT NULL ENABLE);
  ALTER TABLE "FCR"."T#ONLINE_KVIT" ADD CONSTRAINT "T#ONLINE_KVIT_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS#DATA1"  ENABLE;
