--------------------------------------------------------
--  Constraints for Table T#OP_171116
--------------------------------------------------------

  ALTER TABLE "FCR"."T#OP_171116" MODIFY ("C#ID" NOT NULL ENABLE);
  ALTER TABLE "FCR"."T#OP_171116" MODIFY ("C#OPS_ID" NOT NULL ENABLE);
  ALTER TABLE "FCR"."T#OP_171116" MODIFY ("C#ACCOUNT_ID" NOT NULL ENABLE);
  ALTER TABLE "FCR"."T#OP_171116" MODIFY ("C#WORK_ID" NOT NULL ENABLE);
  ALTER TABLE "FCR"."T#OP_171116" MODIFY ("C#DOER_ID" NOT NULL ENABLE);
  ALTER TABLE "FCR"."T#OP_171116" MODIFY ("C#DATE" NOT NULL ENABLE);
  ALTER TABLE "FCR"."T#OP_171116" MODIFY ("C#A_MN" NOT NULL ENABLE);
  ALTER TABLE "FCR"."T#OP_171116" MODIFY ("C#B_MN" NOT NULL ENABLE);
  ALTER TABLE "FCR"."T#OP_171116" MODIFY ("C#TYPE_TAG" NOT NULL ENABLE);
