--------------------------------------------------------
--  DDL for Table T#OPS_KIND
--------------------------------------------------------

  CREATE TABLE "FCR"."T#OPS_KIND" 
   (	"C#ID" NUMBER(*,0), 
	"C#NAME" VARCHAR2(100 BYTE), 
	"C#COD" VARCHAR2(4 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS#DATA1" ;
