--------------------------------------------------------
--  DDL for Table T#OPS_VD_171116
--------------------------------------------------------

  CREATE TABLE "FCR"."T#OPS_VD_171116" 
   (	"C#ID" NUMBER(*,0), 
	"C#VN" NUMBER(*,0), 
	"C#VALID_TAG" VARCHAR2(1 BYTE), 
	"C#SIGN_DATE" DATE, 
	"C#SIGN_S_ID" NUMBER(*,0), 
	"C#KIND_ID" NUMBER(*,0), 
	"C#NOTE_TEXT" VARCHAR2(200 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 16384 NEXT 8192 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS#DATA1" ;

   COMMENT ON COLUMN "FCR"."T#OPS_VD_171116"."C#ID" IS 'Ид хоста.';
   COMMENT ON COLUMN "FCR"."T#OPS_VD_171116"."C#VN" IS 'Номер версии.';
   COMMENT ON COLUMN "FCR"."T#OPS_VD_171116"."C#VALID_TAG" IS 'Действующая {"N":нет;"Y":да}.';
   COMMENT ON COLUMN "FCR"."T#OPS_VD_171116"."C#SIGN_DATE" IS 'Подпись, дата.';
   COMMENT ON COLUMN "FCR"."T#OPS_VD_171116"."C#SIGN_S_ID" IS 'Подпись, ид сессии.';
