--------------------------------------------------------
--  Constraints for Table T#OP_BACK
--------------------------------------------------------

  ALTER TABLE "FCR"."T#OP_BACK" MODIFY ("C#OPS_ID" NOT NULL ENABLE);
  ALTER TABLE "FCR"."T#OP_BACK" MODIFY ("C#ACCOUNT_ID" NOT NULL ENABLE);
  ALTER TABLE "FCR"."T#OP_BACK" MODIFY ("C#WORK_ID" NOT NULL ENABLE);
  ALTER TABLE "FCR"."T#OP_BACK" MODIFY ("C#DOER_ID" NOT NULL ENABLE);
  ALTER TABLE "FCR"."T#OP_BACK" MODIFY ("C#DATE" NOT NULL ENABLE);
  ALTER TABLE "FCR"."T#OP_BACK" MODIFY ("C#A_MN" NOT NULL ENABLE);
  ALTER TABLE "FCR"."T#OP_BACK" MODIFY ("C#B_MN" NOT NULL ENABLE);
  ALTER TABLE "FCR"."T#OP_BACK" MODIFY ("C#TYPE_TAG" NOT NULL ENABLE);
