--------------------------------------------------------
--  Constraints for Table T#OUT_PROC
--------------------------------------------------------

  ALTER TABLE "FCR"."T#OUT_PROC" MODIFY ("C#CODE" NOT NULL ENABLE);
  ALTER TABLE "FCR"."T#OUT_PROC" MODIFY ("C#NAME" NOT NULL ENABLE);
  ALTER TABLE "FCR"."T#OUT_PROC" ADD CONSTRAINT "CP#OUT_PROC" PRIMARY KEY ("C#ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS#DATA1"  ENABLE;
