--------------------------------------------------------
--  Constraints for Table T#PAY_SOURCE
--------------------------------------------------------

  ALTER TABLE "FCR"."T#PAY_SOURCE" MODIFY ("C#ID" NOT NULL ENABLE);
  ALTER TABLE "FCR"."T#PAY_SOURCE" ADD CONSTRAINT "CP#PAY_SOURCE" PRIMARY KEY ("C#ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS#DATA1"  ENABLE;
  ALTER TABLE "FCR"."T#PAY_SOURCE" ADD CONSTRAINT "T#PAY_SOURCE_CHK1" CHECK (C#REAL_DATE >= TO_DATE('01.06.2014','dd.mm.yyyy')) ENABLE;
