--------------------------------------------------------
--  DDL for Table T#PAY_SOURCE
--------------------------------------------------------

  CREATE TABLE "FCR"."T#PAY_SOURCE" 
   (	"C#ID" NUMBER, 
	"C#ACCOUNT" VARCHAR2(30 BYTE), 
	"C#REAL_DATE" DATE, 
	"C#SUMMA" NUMBER, 
	"C#FINE" NUMBER, 
	"C#PERIOD" VARCHAR2(4 BYTE), 
	"C#COD_RKC" VARCHAR2(4 BYTE), 
	"C#PAY_NUM" NUMBER, 
	"C#FILE_ID" NUMBER, 
	"C#TRANSFER_FLG" NUMBER, 
	"C#ACC_ID" NUMBER, 
	"C#ACC_ID_CLOSE" NUMBER, 
	"C#ACC_ID_TTER" NUMBER, 
	"C#OPS_ID" NUMBER, 
	"C#KIND_ID" NUMBER, 
	"C#UPLOAD_FLG" NUMBER, 
	"C#STORNO_ID" NUMBER, 
	"C#DATE" DATE, 
	"C#COMMENT" VARCHAR2(500 BYTE), 
	"C#INN" VARCHAR2(12 BYTE), 
	"C#KPP" VARCHAR2(9 BYTE), 
	"C#PLAT" VARCHAR2(254 BYTE), 
	"C#ROW_TIME" TIMESTAMP (6) DEFAULT sysdate
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 8192 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS#DATA1" ;

   COMMENT ON COLUMN "FCR"."T#PAY_SOURCE"."C#ID" IS 'ID';
   COMMENT ON COLUMN "FCR"."T#PAY_SOURCE"."C#ACCOUNT" IS 'ЛС';
   COMMENT ON COLUMN "FCR"."T#PAY_SOURCE"."C#REAL_DATE" IS 'Дата платежа';
   COMMENT ON COLUMN "FCR"."T#PAY_SOURCE"."C#SUMMA" IS 'Сумма платежа';
   COMMENT ON COLUMN "FCR"."T#PAY_SOURCE"."C#FINE" IS 'Пеня';
   COMMENT ON COLUMN "FCR"."T#PAY_SOURCE"."C#PERIOD" IS 'Период';
   COMMENT ON COLUMN "FCR"."T#PAY_SOURCE"."C#COD_RKC" IS 'Код РКЦ';
   COMMENT ON COLUMN "FCR"."T#PAY_SOURCE"."C#PAY_NUM" IS 'номер платежного документа';
   COMMENT ON COLUMN "FCR"."T#PAY_SOURCE"."C#FILE_ID" IS 'ID файла из которого выполнен перенос';
   COMMENT ON COLUMN "FCR"."T#PAY_SOURCE"."C#TRANSFER_FLG" IS 'Признак переноса платежа в базу';
   COMMENT ON COLUMN "FCR"."T#PAY_SOURCE"."C#OPS_ID" IS 'ID  платежа';
   COMMENT ON COLUMN "FCR"."T#PAY_SOURCE"."C#KIND_ID" IS 'ID типа платежа';
   COMMENT ON COLUMN "FCR"."T#PAY_SOURCE"."C#UPLOAD_FLG" IS '1 - выгружен в РКЦ, для сторонних оплат';
   COMMENT ON COLUMN "FCR"."T#PAY_SOURCE"."C#STORNO_ID" IS 'Ставим порядковый номер сторнированной записи';
   COMMENT ON COLUMN "FCR"."T#PAY_SOURCE"."C#DATE" IS 'Дата отражения платежа в базе';
   COMMENT ON COLUMN "FCR"."T#PAY_SOURCE"."C#COMMENT" IS 'комментарий';
