--------------------------------------------------------
--  DDL for Table T_PERSON
--------------------------------------------------------

  CREATE TABLE "FCR"."T_PERSON" 
   (	"C_ID" NUMBER(10,0), 
	"C_FIRST_NAME" VARCHAR2(100 BYTE), 
	"C_LAST_NAME" VARCHAR2(100 BYTE), 
	"C_MIDDLE_NAME" VARCHAR2(100 BYTE), 
	"C_PHONE" VARCHAR2(20 BYTE), 
	"C_MAIL" VARCHAR2(60 BYTE), 
	"Ñ_FIO_RP" VARCHAR2(200 BYTE), 
	"C_NOTE" VARCHAR2(300 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS#DATA1" ;
