--------------------------------------------------------
--  DDL for Table T#PERSON_J
--------------------------------------------------------

  CREATE TABLE "FCR"."T#PERSON_J" 
   (	"C#PERSON_ID" NUMBER(*,0), 
	"C#NAME" VARCHAR2(250 BYTE), 
	"C#INN_NUM" VARCHAR2(12 BYTE), 
	"C#KPP_NUM" VARCHAR2(9 BYTE), 
	"C#PHONE" VARCHAR2(12 BYTE), 
	"C#CONTACT" VARCHAR2(250 BYTE), 
	"C#NOTE" VARCHAR2(250 BYTE), 
	"C#MAIL" VARCHAR2(120 BYTE), 
	"C#TIP_UL" VARCHAR2(3 BYTE), 
	"C#RAYON" VARCHAR2(40 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS#DATA1" ;

   COMMENT ON COLUMN "FCR"."T#PERSON_J"."C#TIP_UL" IS 'FED-федеральные GUP-гос унит препр MBU-муниц бюдж учр MKU-муниц каз уч MUP-муниц унит предпр OBL-областная собств OMS-орган мест самоупр UL-юрид лицо';
  GRANT FLASHBACK ON "FCR"."T#PERSON_J" TO "NIG";
  GRANT DEBUG ON "FCR"."T#PERSON_J" TO "NIG";
  GRANT QUERY REWRITE ON "FCR"."T#PERSON_J" TO "NIG";
  GRANT ON COMMIT REFRESH ON "FCR"."T#PERSON_J" TO "NIG";
  GRANT REFERENCES ON "FCR"."T#PERSON_J" TO "NIG";
  GRANT UPDATE ON "FCR"."T#PERSON_J" TO "NIG";
  GRANT SELECT ON "FCR"."T#PERSON_J" TO "NIG";
  GRANT INSERT ON "FCR"."T#PERSON_J" TO "NIG";
  GRANT INDEX ON "FCR"."T#PERSON_J" TO "NIG";
  GRANT DELETE ON "FCR"."T#PERSON_J" TO "NIG";
  GRANT ALTER ON "FCR"."T#PERSON_J" TO "NIG";
  GRANT FLASHBACK ON "FCR"."T#PERSON_J" TO "BOG";
  GRANT DEBUG ON "FCR"."T#PERSON_J" TO "BOG";
  GRANT QUERY REWRITE ON "FCR"."T#PERSON_J" TO "BOG";
  GRANT ON COMMIT REFRESH ON "FCR"."T#PERSON_J" TO "BOG";
  GRANT REFERENCES ON "FCR"."T#PERSON_J" TO "BOG";
  GRANT UPDATE ON "FCR"."T#PERSON_J" TO "BOG";
  GRANT SELECT ON "FCR"."T#PERSON_J" TO "BOG";
  GRANT INSERT ON "FCR"."T#PERSON_J" TO "BOG";
  GRANT INDEX ON "FCR"."T#PERSON_J" TO "BOG";
  GRANT DELETE ON "FCR"."T#PERSON_J" TO "BOG";
  GRANT ALTER ON "FCR"."T#PERSON_J" TO "BOG";
  GRANT FLASHBACK ON "FCR"."T#PERSON_J" TO "AUTHENTICATEDUSER";
  GRANT DEBUG ON "FCR"."T#PERSON_J" TO "AUTHENTICATEDUSER";
  GRANT QUERY REWRITE ON "FCR"."T#PERSON_J" TO "AUTHENTICATEDUSER";
  GRANT ON COMMIT REFRESH ON "FCR"."T#PERSON_J" TO "AUTHENTICATEDUSER";
  GRANT UPDATE ON "FCR"."T#PERSON_J" TO "AUTHENTICATEDUSER";
  GRANT SELECT ON "FCR"."T#PERSON_J" TO "AUTHENTICATEDUSER";
  GRANT INSERT ON "FCR"."T#PERSON_J" TO "AUTHENTICATEDUSER";
  GRANT DELETE ON "FCR"."T#PERSON_J" TO "AUTHENTICATEDUSER";
  GRANT ALTER ON "FCR"."T#PERSON_J" TO "AUTHENTICATEDUSER";
