--------------------------------------------------------
--  Constraints for Table T#POSTAMT
--------------------------------------------------------

  ALTER TABLE "FCR"."T#POSTAMT" MODIFY ("C#TYPE_NAME" NOT NULL ENABLE);
  ALTER TABLE "FCR"."T#POSTAMT" MODIFY ("C#NAME" NOT NULL ENABLE);
  ALTER TABLE "FCR"."T#POSTAMT" ADD CONSTRAINT "CC#POSTAMT#C" CHECK (regexp_like(C#CODE,'^[0-9]{6}$')) ENABLE;
  ALTER TABLE "FCR"."T#POSTAMT" ADD CONSTRAINT "CP#POSTAMT" PRIMARY KEY ("C#CODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS#DATA1"  ENABLE;
