--------------------------------------------------------
--  DDL for Table T#POSTAMT
--------------------------------------------------------

  CREATE TABLE "FCR"."T#POSTAMT" 
   (	"C#CODE" VARCHAR2(6 BYTE), 
	"C#PARENT_CODE" VARCHAR2(6 BYTE), 
	"C#TYPE_NAME" VARCHAR2(20 BYTE), 
	"C#NAME" VARCHAR2(50 BYTE), 
	"C#AREA_NAME" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS#DATA1" ;
