--------------------------------------------------------
--  Constraints for Table T#RAW_1C_V101
--------------------------------------------------------

  ALTER TABLE "FCR"."T#RAW_1C_V101" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "FCR"."T#RAW_1C_V101" MODIFY ("ROW_TIME" NOT NULL ENABLE);
  ALTER TABLE "FCR"."T#RAW_1C_V101" ADD CONSTRAINT "T#RAW_1C_V101_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS#DATA1"  ENABLE;
