--------------------------------------------------------
--  DDL for Table T#RAW_DBF
--------------------------------------------------------

  CREATE TABLE "FCR"."T#RAW_DBF" 
   (	"DT_BANK" DATE, 
	"PLP" VARCHAR2(10 BYTE), 
	"DT_PAY" DATE, 
	"OSB" VARCHAR2(20 BYTE), 
	"FILIAL" VARCHAR2(20 BYTE), 
	"CASHIER" VARCHAR2(20 BYTE), 
	"N_OPER" VARCHAR2(20 BYTE), 
	"SUM_PL" NUMBER(*,2), 
	"FIO" VARCHAR2(100 BYTE), 
	"LS" VARCHAR2(50 BYTE), 
	"PERIOD" VARCHAR2(10 BYTE), 
	"EPD" VARCHAR2(10 BYTE), 
	"FILE_NAME" VARCHAR2(100 BYTE), 
	"ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE , 
	"VID_OPER" VARCHAR2(10 BYTE), 
	"FILE_ID" NUMBER, 
	"ROW_TIME" TIMESTAMP (6) DEFAULT systimestamp, 
	"INFO" VARCHAR2(500 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS#DATA1" ;

   COMMENT ON COLUMN "FCR"."T#RAW_DBF"."VID_OPER" IS 'вид операции';
   COMMENT ON COLUMN "FCR"."T#RAW_DBF"."FILE_ID" IS 'FILE_ID для PAY_SOURCE';
   COMMENT ON COLUMN "FCR"."T#RAW_DBF"."INFO" IS 'дополнительный комментарий';
