--------------------------------------------------------
--  DDL for Table T_RESOLUTION
--------------------------------------------------------

  CREATE TABLE "FCR"."T_RESOLUTION" 
   (	"C_ID" NUMBER(10,0), 
	"C_DATE" DATE, 
	"C_NUMBER" VARCHAR2(50 BYTE), 
	"C_DATE_START_PR" DATE, 
	"C_NUMBER_START_PR" VARCHAR2(50 BYTE), 
	"C_DATE_STOP_PR" DATE, 
	"C_NUMBER_STOP_PR" VARCHAR2(50 BYTE), 
	"C_COMMENT" VARCHAR2(200 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS#DATA1" ;
  GRANT FLASHBACK ON "FCR"."T_RESOLUTION" TO "PDO" WITH GRANT OPTION;
  GRANT DEBUG ON "FCR"."T_RESOLUTION" TO "PDO" WITH GRANT OPTION;
  GRANT QUERY REWRITE ON "FCR"."T_RESOLUTION" TO "PDO" WITH GRANT OPTION;
  GRANT ON COMMIT REFRESH ON "FCR"."T_RESOLUTION" TO "PDO" WITH GRANT OPTION;
  GRANT REFERENCES ON "FCR"."T_RESOLUTION" TO "PDO" WITH GRANT OPTION;
  GRANT UPDATE ON "FCR"."T_RESOLUTION" TO "PDO" WITH GRANT OPTION;
  GRANT SELECT ON "FCR"."T_RESOLUTION" TO "PDO" WITH GRANT OPTION;
  GRANT INSERT ON "FCR"."T_RESOLUTION" TO "PDO" WITH GRANT OPTION;
  GRANT ALTER ON "FCR"."T_RESOLUTION" TO "PDO" WITH GRANT OPTION;
  GRANT FLASHBACK ON "FCR"."T_RESOLUTION" TO "TEV" WITH GRANT OPTION;
  GRANT DEBUG ON "FCR"."T_RESOLUTION" TO "TEV" WITH GRANT OPTION;
  GRANT QUERY REWRITE ON "FCR"."T_RESOLUTION" TO "TEV" WITH GRANT OPTION;
  GRANT ON COMMIT REFRESH ON "FCR"."T_RESOLUTION" TO "TEV" WITH GRANT OPTION;
  GRANT REFERENCES ON "FCR"."T_RESOLUTION" TO "TEV" WITH GRANT OPTION;
  GRANT UPDATE ON "FCR"."T_RESOLUTION" TO "TEV" WITH GRANT OPTION;
  GRANT SELECT ON "FCR"."T_RESOLUTION" TO "TEV" WITH GRANT OPTION;
  GRANT INSERT ON "FCR"."T_RESOLUTION" TO "TEV" WITH GRANT OPTION;
  GRANT INDEX ON "FCR"."T_RESOLUTION" TO "TEV" WITH GRANT OPTION;
  GRANT DELETE ON "FCR"."T_RESOLUTION" TO "TEV" WITH GRANT OPTION;
  GRANT ALTER ON "FCR"."T_RESOLUTION" TO "TEV" WITH GRANT OPTION;
  GRANT INDEX ON "FCR"."T_RESOLUTION" TO "PDO" WITH GRANT OPTION;
  GRANT DELETE ON "FCR"."T_RESOLUTION" TO "PDO" WITH GRANT OPTION;
