--------------------------------------------------------
--  Constraints for Table T#ROOMS_SPEC
--------------------------------------------------------

  ALTER TABLE "FCR"."T#ROOMS_SPEC" MODIFY ("C#ROOMS_ID" NOT NULL ENABLE);
  ALTER TABLE "FCR"."T#ROOMS_SPEC" MODIFY ("C#DATE" NOT NULL ENABLE);
  ALTER TABLE "FCR"."T#ROOMS_SPEC" ADD CONSTRAINT "CP#ROOMS_SPEC" PRIMARY KEY ("C#ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS#DATA1"  ENABLE;
  ALTER TABLE "FCR"."T#ROOMS_SPEC" ADD CONSTRAINT "CU#ROOMS_SPEC" UNIQUE ("C#ROOMS_ID", "C#DATE") DISABLE;
