--------------------------------------------------------
--  DDL for Table T#ROOMS_PART
--------------------------------------------------------

  CREATE TABLE "FCR"."T#ROOMS_PART" 
   (	"C#ROOMS_ID" NUMBER(*,0), 
	"C#ROOMS_PN" NUMBER(*,0), 
	 CONSTRAINT "CP#ROOMS_PART" PRIMARY KEY ("C#ROOMS_ID", "C#ROOMS_PN") ENABLE
   ) ORGANIZATION INDEX NOCOMPRESS PCTFREE 10 INITRANS 2 MAXTRANS 255 LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS#DATA1" 
 PCTTHRESHOLD 50;
