--------------------------------------------------------
--  DDL for Table T_ROOM68
--------------------------------------------------------

  CREATE TABLE "FCR"."T_ROOM68" 
   (	"ROOMID" VARCHAR2(36 BYTE), 
	"ROOMGUID" VARCHAR2(36 BYTE), 
	"HOUSEGUID" VARCHAR2(36 BYTE), 
	"REGIONCODE" VARCHAR2(2 BYTE), 
	"FLATNUMBER" VARCHAR2(50 BYTE), 
	"FLATTYPE" NUMBER(*,0), 
	"ROOMNUMBER" VARCHAR2(50 BYTE), 
	"ROOMTYPE" VARCHAR2(2 BYTE), 
	"CADNUM" VARCHAR2(100 BYTE), 
	"ROOMCADNUM" VARCHAR2(100 BYTE), 
	"POSTALCODE" VARCHAR2(6 BYTE), 
	"UPDATEDATE" DATE, 
	"PREVID" VARCHAR2(36 BYTE), 
	"NEXTID" VARCHAR2(36 BYTE), 
	"OPERSTATUS" NUMBER(*,0), 
	"STARTDATE" DATE, 
	"ENDDATE" DATE, 
	"LIVESTATUS" NUMBER(*,0), 
	"NORMDOC" VARCHAR2(36 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS#DATA1" ;
