--------------------------------------------------------
--  DDL for Table T_SITE
--------------------------------------------------------

  CREATE TABLE "FCR"."T_SITE" 
   (	"C_ID" NUMBER(10,0), 
	"C_SITE" VARCHAR2(100 BYTE), 
	"C_ID_COURT" NUMBER(10,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS#DATA1" ;

   COMMENT ON COLUMN "FCR"."T_SITE"."C_ID" IS 'Ид. участка';
   COMMENT ON COLUMN "FCR"."T_SITE"."C_SITE" IS 'Наименование участка';
   COMMENT ON COLUMN "FCR"."T_SITE"."C_ID_COURT" IS 'Ид. суда';
