--------------------------------------------------------
--  Constraints for Table T_SITE
--------------------------------------------------------

  ALTER TABLE "FCR"."T_SITE" MODIFY ("C_ID" NOT NULL ENABLE);
  ALTER TABLE "FCR"."T_SITE" MODIFY ("C_ID_COURT" NOT NULL ENABLE);
  ALTER TABLE "FCR"."T_SITE" ADD CONSTRAINT "T_SITE_PK" PRIMARY KEY ("C_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS#DATA1"  ENABLE;
