--------------------------------------------------------
--  DDL for Table T_SOCRBASE68
--------------------------------------------------------

  CREATE TABLE "FCR"."T_SOCRBASE68" 
   (	"C_LEVEL" NUMBER(3,0), 
	"SOCRNAME" VARCHAR2(128 BYTE), 
	"SCNAME" VARCHAR2(26 BYTE), 
	"KOD_T_ST" NUMBER(5,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS#DATA1" ;
