--------------------------------------------------------
--  DDL for Table T_STATUS_CLAIM_VD
--------------------------------------------------------

  CREATE TABLE "FCR"."T_STATUS_CLAIM_VD" 
   (	"T_SCLAIMC_ID" NUMBER(10,0), 
	"C_DATE" DATE, 
	"C_VN" NUMBER(10,0), 
	"C_VALID_TAG" NVARCHAR2(1), 
	"C_SIGN_S_ID" NUMBER(10,0), 
	"C_SIGN_DATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS#DATA1" ;
