--------------------------------------------------------
--  DDL for Table T_STATUS_CLAIM
--------------------------------------------------------

  CREATE TABLE "FCR"."T_STATUS_CLAIM" 
   (	"C_ID" NUMBER(10,0), 
	"T_CLAIMC_ID" NUMBER(10,0), 
	"T_TSTATUSC_ID" NUMBER(10,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS#DATA1" ;
