--------------------------------------------------------
--  DDL for Index T_STATUS_CLAIM_VD_T_SCLAIMC_ID
--------------------------------------------------------

  CREATE INDEX "FCR"."T_STATUS_CLAIM_VD_T_SCLAIMC_ID" ON "FCR"."T_STATUS_CLAIM_VD" ("T_SCLAIMC_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS#DATA1" ;
