--------------------------------------------------------
--  DDL for Index T_ST_RESOLUTION_T_TYPE_SRC_ID
--------------------------------------------------------

  CREATE INDEX "FCR"."T_ST_RESOLUTION_T_TYPE_SRC_ID" ON "FCR"."T_ST_RESOLUTION" ("T_TYPE_SRC_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS#DATA1" ;
