--------------------------------------------------------
--  Constraints for Table T#STORAGE
--------------------------------------------------------

  ALTER TABLE "FCR"."T#STORAGE" MODIFY ("C#C_VOL" NOT NULL ENABLE);
  ALTER TABLE "FCR"."T#STORAGE" MODIFY ("C#C2_VOL" NOT NULL ENABLE);
  ALTER TABLE "FCR"."T#STORAGE" MODIFY ("C#C_SUM" NOT NULL ENABLE);
  ALTER TABLE "FCR"."T#STORAGE" MODIFY ("C#C2_SUM" NOT NULL ENABLE);
  ALTER TABLE "FCR"."T#STORAGE" MODIFY ("C#MC_SUM" NOT NULL ENABLE);
  ALTER TABLE "FCR"."T#STORAGE" MODIFY ("C#M_SUM" NOT NULL ENABLE);
  ALTER TABLE "FCR"."T#STORAGE" MODIFY ("C#MP_SUM" NOT NULL ENABLE);
  ALTER TABLE "FCR"."T#STORAGE" MODIFY ("C#P_SUM" NOT NULL ENABLE);
  ALTER TABLE "FCR"."T#STORAGE" MODIFY ("C#FC_SUM" NOT NULL ENABLE);
  ALTER TABLE "FCR"."T#STORAGE" MODIFY ("C#FP_SUM" NOT NULL ENABLE);
  ALTER TABLE "FCR"."T#STORAGE" ADD CONSTRAINT "CP#STORAGE" PRIMARY KEY ("C#ACCOUNT_ID", "C#WORK_ID", "C#DOER_ID", "C#MN")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS#DATA1"  ENABLE;
