--------------------------------------------------------
--  DDL for Table T#SUPPORT_DOCUMS
--------------------------------------------------------

  CREATE TABLE "FCR"."T#SUPPORT_DOCUMS" 
   (	"C#TABLE_PARENT" VARCHAR2(20 BYTE), 
	"C#DATE_FILE" DATE, 
	"C#FILE" BLOB, 
	"C#ID" NUMBER(*,0), 
	"C#DESCRIPTION" VARCHAR2(255 BYTE), 
	"C#ID_RECORD" NUMBER(*,0), 
	"C#EXT" VARCHAR2(5 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS#DATA1" 
 LOB ("C#FILE") STORE AS SECUREFILE (
  TABLESPACE "TS#DATA1" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
  GRANT FLASHBACK ON "FCR"."T#SUPPORT_DOCUMS" TO "PDO";
  GRANT DEBUG ON "FCR"."T#SUPPORT_DOCUMS" TO "PDO";
  GRANT QUERY REWRITE ON "FCR"."T#SUPPORT_DOCUMS" TO "PDO";
  GRANT ON COMMIT REFRESH ON "FCR"."T#SUPPORT_DOCUMS" TO "PDO";
  GRANT REFERENCES ON "FCR"."T#SUPPORT_DOCUMS" TO "PDO";
  GRANT UPDATE ON "FCR"."T#SUPPORT_DOCUMS" TO "PDO";
  GRANT SELECT ON "FCR"."T#SUPPORT_DOCUMS" TO "PDO";
  GRANT INSERT ON "FCR"."T#SUPPORT_DOCUMS" TO "PDO";
  GRANT INDEX ON "FCR"."T#SUPPORT_DOCUMS" TO "PDO";
  GRANT DELETE ON "FCR"."T#SUPPORT_DOCUMS" TO "PDO";
  GRANT ALTER ON "FCR"."T#SUPPORT_DOCUMS" TO "PDO";
  GRANT FLASHBACK ON "FCR"."T#SUPPORT_DOCUMS" TO "KAN";
  GRANT DEBUG ON "FCR"."T#SUPPORT_DOCUMS" TO "KAN";
  GRANT QUERY REWRITE ON "FCR"."T#SUPPORT_DOCUMS" TO "KAN";
  GRANT ON COMMIT REFRESH ON "FCR"."T#SUPPORT_DOCUMS" TO "KAN";
  GRANT REFERENCES ON "FCR"."T#SUPPORT_DOCUMS" TO "KAN";
  GRANT UPDATE ON "FCR"."T#SUPPORT_DOCUMS" TO "KAN";
  GRANT SELECT ON "FCR"."T#SUPPORT_DOCUMS" TO "KAN";
  GRANT INSERT ON "FCR"."T#SUPPORT_DOCUMS" TO "KAN";
  GRANT INDEX ON "FCR"."T#SUPPORT_DOCUMS" TO "KAN";
  GRANT ALTER ON "FCR"."T#SUPPORT_DOCUMS" TO "KAN";
  GRANT FLASHBACK ON "FCR"."T#SUPPORT_DOCUMS" TO "MAB";
  GRANT DEBUG ON "FCR"."T#SUPPORT_DOCUMS" TO "MAB";
  GRANT QUERY REWRITE ON "FCR"."T#SUPPORT_DOCUMS" TO "MAB";
  GRANT ON COMMIT REFRESH ON "FCR"."T#SUPPORT_DOCUMS" TO "MAB";
  GRANT REFERENCES ON "FCR"."T#SUPPORT_DOCUMS" TO "MAB";
  GRANT UPDATE ON "FCR"."T#SUPPORT_DOCUMS" TO "MAB";
  GRANT SELECT ON "FCR"."T#SUPPORT_DOCUMS" TO "MAB";
  GRANT INSERT ON "FCR"."T#SUPPORT_DOCUMS" TO "MAB";
  GRANT INDEX ON "FCR"."T#SUPPORT_DOCUMS" TO "MAB";
  GRANT DELETE ON "FCR"."T#SUPPORT_DOCUMS" TO "MAB";
  GRANT DELETE ON "FCR"."T#SUPPORT_DOCUMS" TO "KAN";
  GRANT ALTER ON "FCR"."T#SUPPORT_DOCUMS" TO "MAB";
