--------------------------------------------------------
--  DDL for Table T#TEMP_STROITEL_ACC_IDS
--------------------------------------------------------

  CREATE TABLE "FCR"."T#TEMP_STROITEL_ACC_IDS" 
   (	"LS" VARCHAR2(20 BYTE), 
	"ACC_ID" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS#DATA1" ;
