--------------------------------------------------------
--  Constraints for Table T_TEMPLATE_RESOLUTION
--------------------------------------------------------

  ALTER TABLE "FCR"."T_TEMPLATE_RESOLUTION" ADD CONSTRAINT "T_TEMPLATE_RESOLUTION_PK" PRIMARY KEY ("C_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "TS#DATA1"  ENABLE;
  ALTER TABLE "FCR"."T_TEMPLATE_RESOLUTION" MODIFY ("C_ID" NOT NULL ENABLE);
