--------------------------------------------------------
--  DDL for Table T#TEMP_DATE_1ST_PAY
--------------------------------------------------------

  CREATE TABLE "FCR"."T#TEMP_DATE_1ST_PAY" 
   (	"ACC_ID" NUMBER(*,0), 
	"ACC_NUM" VARCHAR2(20 BYTE), 
	"DATE1" VARCHAR2(10 BYTE), 
	"DOLG" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS#DATA1" ;
