--------------------------------------------------------
--  DDL for Table T#TEMP_POST_ALL
--------------------------------------------------------

  CREATE TABLE "FCR"."T#TEMP_POST_ALL" 
   (	"DT_BANK" VARCHAR2(26 BYTE), 
	"PLP" VARCHAR2(26 BYTE), 
	"DT_PAY" DATE, 
	"OSB" VARCHAR2(26 BYTE), 
	"FILIAL" VARCHAR2(10 BYTE), 
	"CASHIER" VARCHAR2(26 BYTE), 
	"N_OPER" VARCHAR2(10 BYTE), 
	"SUM_PL" NUMBER(8,2), 
	"FIO" VARCHAR2(50 BYTE), 
	"LS" VARCHAR2(50 BYTE), 
	"PERIOD" VARCHAR2(26 BYTE), 
	"EPD" VARCHAR2(10 BYTE), 
	"FILE_NAME" VARCHAR2(128 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS#DATA1" ;
