--------------------------------------------------------
--  Constraints for Table T_TEMPLATE_CLAIM
--------------------------------------------------------

  ALTER TABLE "FCR"."T_TEMPLATE_CLAIM" ADD CONSTRAINT "T_TEMPLATE_CLAIM_PK" PRIMARY KEY ("C_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "TS#DATA1"  ENABLE;
  ALTER TABLE "FCR"."T_TEMPLATE_CLAIM" MODIFY ("C_ID" NOT NULL ENABLE);
  ALTER TABLE "FCR"."T_TEMPLATE_CLAIM" MODIFY ("C_CLAIM_ID" NOT NULL ENABLE);
