--------------------------------------------------------
--  DDL for Table T#TEMP_PAY_STROITEL_2018_01
--------------------------------------------------------

  CREATE TABLE "FCR"."T#TEMP_PAY_STROITEL_2018_01" 
   (	"LSO" NUMBER(20,0), 
	"DATA_OLD" VARCHAR2(26 BYTE), 
	"PER" VARCHAR2(20 BYTE), 
	"OPL_KAPREM" NUMBER(15,2), 
	"IDORG" VARCHAR2(20 BYTE), 
	"ACC_ID" NUMBER, 
	"PER2" VARCHAR2(20 BYTE), 
	"RKC" VARCHAR2(20 BYTE), 
	"DATA_OPL" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS#DATA1" ;
