--------------------------------------------------------
--  DDL for Table T#TEMP_STROITEL_2017_11
--------------------------------------------------------

  CREATE TABLE "FCR"."T#TEMP_STROITEL_2017_11" 
   (	"NAS_PUNKT" VARCHAR2(26 BYTE), 
	"UL" VARCHAR2(26 BYTE), 
	"DOM" VARCHAR2(20 BYTE), 
	"DOP" VARCHAR2(26 BYTE), 
	"KV" VARCHAR2(26 BYTE), 
	"LS" VARCHAR2(20 BYTE), 
	"SALDO" NUMBER(9,2), 
	"OPLATA" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS#DATA1" ;
