--------------------------------------------------------
--  DDL for Table T_TMP_MORDOVO_10
--------------------------------------------------------

  CREATE TABLE "FCR"."T_TMP_MORDOVO_10" 
   (	"N_HOUSE" VARCHAR2(26 BYTE), 
	"FIO" VARCHAR2(128 BYTE), 
	"KV" VARCHAR2(10 BYTE), 
	"AREA" NUMBER(5,1)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS#DATA1" ;
