--------------------------------------------------------
--  DDL for Table T#TOTAL_HOUSE_TMP2
--------------------------------------------------------

  CREATE TABLE "FCR"."T#TOTAL_HOUSE_TMP2" 
   (	"HOUSE_ID" NUMBER, 
	"MN" NUMBER, 
	"PERIOD" VARCHAR2(4000 BYTE), 
	"CHARGE_SUM_MN" NUMBER, 
	"CHARGE_SUM_TOTAL" NUMBER, 
	"PAY_SUM_MN" NUMBER, 
	"PAY_SUM_TOTAL" NUMBER, 
	"PENI_SUM_MN" NUMBER, 
	"PENI_SUM_TOTAL" NUMBER, 
	"BARTER_SUM_MN" NUMBER, 
	"BARTER_SUM_TOTAL" NUMBER, 
	"DOLG_SUM_MN" NUMBER, 
	"DOLG_SUM_TOTAL" NUMBER, 
	"JOB_SUM_MN" NUMBER, 
	"JOB_SUM_TOTAL" NUMBER, 
	"OWNERS_JOB_SUM_MN" NUMBER, 
	"OWNERS_JOB_SUM_TOTAL" NUMBER, 
	"GOS_JOB_SUM_MN" NUMBER, 
	"GOS_JOB_SUM_TOTAL" NUMBER, 
	"BALANCE_SUM_MN" NUMBER, 
	"BALANCE_SUM_TOTAL" NUMBER, 
	"ROW_TIME" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS#DATA1" ;
