--------------------------------------------------------
--  DDL for Table T#TOTAL_ACCOUNT
--------------------------------------------------------

  CREATE TABLE "FCR"."T#TOTAL_ACCOUNT" 
   (	"HOUSE_ID" NUMBER(*,0), 
	"ROOMS_ID" NUMBER(*,0), 
	"FLAT_NUM" VARCHAR2(50 BYTE), 
	"ACCOUNT_ID" NUMBER(*,0), 
	"END_ACCOUNT_MN" NUMBER, 
	"MN" NUMBER(4,0), 
	"PERIOD" VARCHAR2(10 BYTE), 
	"CHARGE_SUM_MN" NUMBER, 
	"CHARGE_SUM_TOTAL" NUMBER, 
	"PAY_SUM_MN" NUMBER, 
	"PAY_SUM_TOTAL" NUMBER, 
	"PENI_SUM_MN" NUMBER, 
	"PENI_SUM_TOTAL" NUMBER, 
	"BARTER_SUM_MN" NUMBER, 
	"BARTER_SUM_TOTAL" NUMBER, 
	"DOLG_SUM_MN" NUMBER, 
	"DOLG_SUM_TOTAL" NUMBER, 
	"ROW_TIME" TIMESTAMP (6) DEFAULT sysdate
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS NOLOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS#DATA1" ;
