--------------------------------------------------------
--  DDL for Table T#TRANS_2014
--------------------------------------------------------

  CREATE TABLE "FCR"."T#TRANS_2014" 
   (	"ADDRESS" VARCHAR2(128 BYTE), 
	"HOUSE_ID" NUMBER(6,0), 
	"SUM_1" NUMBER(22,13), 
	"SUM_2" NUMBER(20,11), 
	"OST" NUMBER(35,27)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS#DATA1" ;
