--------------------------------------------------------
--  DDL for Table T_TYPE_COURT
--------------------------------------------------------

  CREATE TABLE "FCR"."T_TYPE_COURT" 
   (	"C_ID" NUMBER(10,0), 
	"C_TYPE" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS#DATA1" ;

   COMMENT ON COLUMN "FCR"."T_TYPE_COURT"."C_ID" IS 'Идентификатор типа суда';
   COMMENT ON COLUMN "FCR"."T_TYPE_COURT"."C_TYPE" IS 'Тип суда';
