--------------------------------------------------------
--  Constraints for Table T#WORKS
--------------------------------------------------------

  ALTER TABLE "FCR"."T#WORKS" MODIFY ("C#SERVICE_ID" NOT NULL ENABLE);
  ALTER TABLE "FCR"."T#WORKS" MODIFY ("C#NAME" NOT NULL ENABLE);
  ALTER TABLE "FCR"."T#WORKS" ADD CONSTRAINT "CP#WORKS" PRIMARY KEY ("C#ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS#DATA1"  ENABLE;
  ALTER TABLE "FCR"."T#WORKS" ADD CONSTRAINT "CU#WORKS" UNIQUE ("C#SERVICE_ID", "C#NAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS#DATA1"  ENABLE;
