--------------------------------------------------------
--  Constraints for Table TEMP_DEL
--------------------------------------------------------

  ALTER TABLE "FCR"."TEMP_DEL" MODIFY ("C#OPS_ID" NOT NULL ENABLE);
  ALTER TABLE "FCR"."TEMP_DEL" MODIFY ("C#ACCOUNT_ID" NOT NULL ENABLE);
  ALTER TABLE "FCR"."TEMP_DEL" MODIFY ("C#WORK_ID" NOT NULL ENABLE);
  ALTER TABLE "FCR"."TEMP_DEL" MODIFY ("C#DOER_ID" NOT NULL ENABLE);
  ALTER TABLE "FCR"."TEMP_DEL" MODIFY ("C#DATE" NOT NULL ENABLE);
  ALTER TABLE "FCR"."TEMP_DEL" MODIFY ("C#A_MN" NOT NULL ENABLE);
  ALTER TABLE "FCR"."TEMP_DEL" MODIFY ("C#B_MN" NOT NULL ENABLE);
  ALTER TABLE "FCR"."TEMP_DEL" MODIFY ("C#TYPE_TAG" NOT NULL ENABLE);
  ALTER TABLE "FCR"."TEMP_DEL" MODIFY ("C#VALID_TAG" NOT NULL ENABLE);
  ALTER TABLE "FCR"."TEMP_DEL" MODIFY ("C#SIGN_DATE" NOT NULL ENABLE);
  ALTER TABLE "FCR"."TEMP_DEL" MODIFY ("C#SIGN_S_ID" NOT NULL ENABLE);
