--------------------------------------------------------
--  DDL for Table TT#ACCOUNTS_ADRESES
--------------------------------------------------------

  CREATE TABLE "FCR"."TT#ACCOUNTS_ADRESES" 
   (	"C#ROOMS_ID" NUMBER(*,0), 
	"C#NUM" VARCHAR2(20 BYTE), 
	"C#DATE" DATE, 
	"C#END_DATE" DATE, 
	"ADRES" VARCHAR2(4000 BYTE), 
	"C#NUM_OUT" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS#DATA1" ;
