--------------------------------------------------------
--  DDL for Table TT#CHARGE_PAY_J
--------------------------------------------------------

  CREATE TABLE "FCR"."TT#CHARGE_PAY_J" 
   (	"C#ACCOUNT_ID" NUMBER(*,0), 
	"C#ACC_NUM" VARCHAR2(20 BYTE), 
	"C#A_MN" NUMBER(4,0), 
	"CHARGE_SUM" NUMBER, 
	"PAY_SUM" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS#DATA1" ;
