--------------------------------------------------------
--  DDL for Table TT#HOUSE_IDS
--------------------------------------------------------

  CREATE TABLE "FCR"."TT#HOUSE_IDS" 
   (	"ID_HOUS" VARCHAR2(10 BYTE), 
	"POSTCOD" VARCHAR2(10 BYTE), 
	"COMMENT_STR" VARCHAR2(200 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS#DATA1" ;
