--------------------------------------------------------
--  DDL for Table TT#HOUSES_NOTGUIDS
--------------------------------------------------------

  CREATE TABLE "FCR"."TT#HOUSES_NOTGUIDS" 
   (	"COLUMN1" NUMBER(6,0), 
	"COLUMN2" VARCHAR2(128 BYTE), 
	"COLUMN3" VARCHAR2(128 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS#DATA1" ;
