--------------------------------------------------------
--  DDL for Table TT#HOUSE_INFO_NADEGDINA
--------------------------------------------------------

  CREATE TABLE "FCR"."TT#HOUSE_INFO_NADEGDINA" 
   (	"N_PROG" NVARCHAR2(200), 
	"PRIM" NVARCHAR2(250), 
	"RAYOM" NVARCHAR2(250), 
	"MUN_OBR" NVARCHAR2(250), 
	"ADR1" NVARCHAR2(250), 
	"ADR2" NVARCHAR2(250), 
	"AREA_OBSH" NVARCHAR2(250), 
	"AREA_GIL" NVARCHAR2(250), 
	"PLAN_LIFT" NVARCHAR2(250), 
	"PLAN_FUND" NVARCHAR2(250), 
	"SPOSOB" NVARCHAR2(250), 
	"BANK" NVARCHAR2(250), 
	"BANK_ACC" NVARCHAR2(250), 
	"MES_PLAT" NVARCHAR2(250), 
	"TSG_UK" NVARCHAR2(250), 
	"PROT_N" NVARCHAR2(250), 
	"PROT_DATE" NVARCHAR2(250), 
	"IZM_DATE" NVARCHAR2(250), 
	"PREG_SPOSOB" NVARCHAR2(250), 
	"PREG_PROT_N" NVARCHAR2(250), 
	"PREG_PROT_DATE" NVARCHAR2(250), 
	"PREG_ACC" NVARCHAR2(250)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS#DATA1" ;

   COMMENT ON TABLE "FCR"."TT#HOUSE_INFO_NADEGDINA"  IS 'загружено из d:\!SQL\!GIS\Надеждина\1 ИНФ. О СПОСОБЕ ФОРМИРОВАНИЯ ПРОГРАММА  кап. ремонта НОВАЯ.xlsx';
