--------------------------------------------------------
--  DDL for Table TT#KONTRA
--------------------------------------------------------

  CREATE TABLE "FCR"."TT#KONTRA" 
   (	"NAME" VARCHAR2(128 BYTE), 
	"FULL_NAME" VARCHAR2(256 BYTE), 
	"INN" NUMBER(14,0), 
	"KPP" NUMBER(9,0), 
	"NAME2" VARCHAR2(100 BYTE), 
	"ID_1C" NUMBER(6,0), 
	"ACC" NUMBER(20,0), 
	"BIK" NUMBER(8,0), 
	"KOR" NUMBER(20,0), 
	"BANK_NAME" VARCHAR2(45 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS#DATA1" ;
