--------------------------------------------------------
--  DDL for Table TT#LAST_TEPLORESURS
--------------------------------------------------------

  CREATE TABLE "FCR"."TT#LAST_TEPLORESURS" 
   (	"C#ACCOUNT_ID" NUMBER(*,0), 
	"C#HOUSE_ID" NUMBER(*,0), 
	"C#FLAT_NUM" VARCHAR2(50 BYTE), 
	"C#HOUSE_NUM" VARCHAR2(20 BYTE), 
	"C#ROOMS_ID" NUMBER(*,0), 
	"C#ROOMS_PN" NUMBER(*,0), 
	"C#ACC_DATE" DATE, 
	"C#ACC_NUM" VARCHAR2(20 BYTE), 
	"C#SN" NUMBER(*,0), 
	"C#VD_VN" NUMBER(*,0), 
	"C#VD_SIGN_DATE" DATE, 
	"C#VD_SIGN_S_ID" NUMBER(*,0), 
	"C#SPEC_DATE" DATE, 
	"C#SPEC_VN" NUMBER(*,0), 
	"C#SPEC_SIGN_DATE" DATE, 
	"C#SPEC_SIGN_S_ID" NUMBER(*,0), 
	"C#PERSON_ID" NUMBER(*,0), 
	"C#PART_COEF" NUMBER, 
	"C#OP_DATE" DATE, 
	"C#OUT_PROC_ID" NUMBER(*,0), 
	"C#OUT_NUM" VARCHAR2(20 BYTE), 
	"C#RKC_CODE" VARCHAR2(3 BYTE), 
	"C#RKC_NAME" VARCHAR2(100 BYTE), 
	"ADDR" VARCHAR2(100 BYTE), 
	"ADDR_LIKE" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS#DATA1" ;
