--------------------------------------------------------
--  DDL for Table TT#LGOT_SOC_FOR_DOLG
--------------------------------------------------------

  CREATE TABLE "FCR"."TT#LGOT_SOC_FOR_DOLG" 
   (	"NN" NUMBER(5,0), 
	"ADDR" VARCHAR2(300 BYTE), 
	"ACC_NUM" VARCHAR2(20 BYTE), 
	"FIO" VARCHAR2(200 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS#DATA1" ;
