--------------------------------------------------------
--  DDL for Table TT#LST#GET_PAY_RKC
--------------------------------------------------------

  CREATE TABLE "FCR"."TT#LST#GET_PAY_RKC" 
   (	"C#ID" NUMBER, 
	"ACCOUNT_ID" NUMBER(*,0), 
	"C#DATE" DATE, 
	"C#END_DATE" DATE, 
	"C#LIVING_TAG" VARCHAR2(1 BYTE), 
	"C#OWN_TYPE_TAG" VARCHAR2(1 BYTE), 
	"C#AREA_VAL" NUMBER, 
	"HOUSE_ID" NUMBER, 
	"PERSON_ID" NUMBER, 
	"OUT_ACCOUNT_NUM" VARCHAR2(20 BYTE), 
	"ACCOUNT_NUM" VARCHAR2(20 BYTE), 
	"ADDR_PATH" VARCHAR2(4000 BYTE), 
	"C#HOUSE_NUM" VARCHAR2(42 BYTE), 
	"C#FLAT_NUM" VARCHAR2(50 BYTE), 
	"ROOM_ID" NUMBER(*,0), 
	"PERSON" VARCHAR2(4000 BYTE), 
	"URFIZ" CHAR(12 BYTE), 
	"C#OUT_PROC_ID" NUMBER(*,0), 
	"C#CODE" VARCHAR2(3 BYTE), 
	"C#REAL_DATE" DATE, 
	"C#SUMMA" NUMBER, 
	"C#ACCOUNT" VARCHAR2(30 BYTE), 
	"C#PERIOD" VARCHAR2(4 BYTE), 
	"C#COD_RKC" VARCHAR2(4 BYTE), 
	"C#FILE_ID" NUMBER, 
	"C#NAME" VARCHAR2(100 BYTE), 
	"C#COD" VARCHAR2(4 BYTE), 
	"UK_NAME" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS#DATA1" ;
