--------------------------------------------------------
--  Constraints for Table TT#LAST_TEPLORESURS
--------------------------------------------------------

  ALTER TABLE "FCR"."TT#LAST_TEPLORESURS" MODIFY ("C#HOUSE_ID" NOT NULL ENABLE);
  ALTER TABLE "FCR"."TT#LAST_TEPLORESURS" MODIFY ("C#FLAT_NUM" NOT NULL ENABLE);
  ALTER TABLE "FCR"."TT#LAST_TEPLORESURS" MODIFY ("C#HOUSE_NUM" NOT NULL ENABLE);
  ALTER TABLE "FCR"."TT#LAST_TEPLORESURS" MODIFY ("C#ROOMS_ID" NOT NULL ENABLE);
  ALTER TABLE "FCR"."TT#LAST_TEPLORESURS" MODIFY ("C#ROOMS_PN" NOT NULL ENABLE);
  ALTER TABLE "FCR"."TT#LAST_TEPLORESURS" MODIFY ("C#ACC_DATE" NOT NULL ENABLE);
  ALTER TABLE "FCR"."TT#LAST_TEPLORESURS" MODIFY ("C#ACC_NUM" NOT NULL ENABLE);
  ALTER TABLE "FCR"."TT#LAST_TEPLORESURS" MODIFY ("C#SN" NOT NULL ENABLE);
  ALTER TABLE "FCR"."TT#LAST_TEPLORESURS" MODIFY ("C#VD_SIGN_DATE" NOT NULL ENABLE);
  ALTER TABLE "FCR"."TT#LAST_TEPLORESURS" MODIFY ("C#VD_SIGN_S_ID" NOT NULL ENABLE);
  ALTER TABLE "FCR"."TT#LAST_TEPLORESURS" MODIFY ("C#SPEC_DATE" NOT NULL ENABLE);
  ALTER TABLE "FCR"."TT#LAST_TEPLORESURS" MODIFY ("C#SPEC_SIGN_DATE" NOT NULL ENABLE);
  ALTER TABLE "FCR"."TT#LAST_TEPLORESURS" MODIFY ("C#SPEC_SIGN_S_ID" NOT NULL ENABLE);
  ALTER TABLE "FCR"."TT#LAST_TEPLORESURS" MODIFY ("C#OP_DATE" NOT NULL ENABLE);
  ALTER TABLE "FCR"."TT#LAST_TEPLORESURS" MODIFY ("C#RKC_CODE" NOT NULL ENABLE);
  ALTER TABLE "FCR"."TT#LAST_TEPLORESURS" MODIFY ("C#RKC_NAME" NOT NULL ENABLE);
