--------------------------------------------------------
--  Constraints for Table TT#LST#GET_PAY_RKC
--------------------------------------------------------

  ALTER TABLE "FCR"."TT#LST#GET_PAY_RKC" MODIFY ("C#ID" NOT NULL ENABLE);
  ALTER TABLE "FCR"."TT#LST#GET_PAY_RKC" MODIFY ("C#DATE" NOT NULL ENABLE);
  ALTER TABLE "FCR"."TT#LST#GET_PAY_RKC" MODIFY ("C#FLAT_NUM" NOT NULL ENABLE);
  ALTER TABLE "FCR"."TT#LST#GET_PAY_RKC" MODIFY ("C#CODE" NOT NULL ENABLE);
  ALTER TABLE "FCR"."TT#LST#GET_PAY_RKC" MODIFY ("C#NAME" NOT NULL ENABLE);
  ALTER TABLE "FCR"."TT#LST#GET_PAY_RKC" MODIFY ("C#COD" NOT NULL ENABLE);
