--------------------------------------------------------
--  Constraints for Table TT#OP_20181009
--------------------------------------------------------

  ALTER TABLE "FCR"."TT#OP_20181009" MODIFY ("C#OPS_ID" NOT NULL ENABLE);
  ALTER TABLE "FCR"."TT#OP_20181009" MODIFY ("C#ACCOUNT_ID" NOT NULL ENABLE);
  ALTER TABLE "FCR"."TT#OP_20181009" MODIFY ("C#WORK_ID" NOT NULL ENABLE);
  ALTER TABLE "FCR"."TT#OP_20181009" MODIFY ("C#DOER_ID" NOT NULL ENABLE);
  ALTER TABLE "FCR"."TT#OP_20181009" MODIFY ("C#DATE" NOT NULL ENABLE);
  ALTER TABLE "FCR"."TT#OP_20181009" MODIFY ("C#A_MN" NOT NULL ENABLE);
  ALTER TABLE "FCR"."TT#OP_20181009" MODIFY ("C#B_MN" NOT NULL ENABLE);
  ALTER TABLE "FCR"."TT#OP_20181009" MODIFY ("C#TYPE_TAG" NOT NULL ENABLE);
