--------------------------------------------------------
--  DDL for Table TT#PODRYAD
--------------------------------------------------------

  CREATE TABLE "FCR"."TT#PODRYAD" 
   (	"ID_1C" NUMBER(6,0), 
	"NAME" VARCHAR2(128 BYTE), 
	"FULL_NAME" VARCHAR2(256 BYTE), 
	"INN" NUMBER(14,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS#DATA1" ;
