--------------------------------------------------------
--  Constraints for Table TT#PB_DATA_JP
--------------------------------------------------------

  ALTER TABLE "FCR"."TT#PB_DATA_JP" MODIFY ("C#ACCOUNT_ID" NOT NULL ENABLE);
  ALTER TABLE "FCR"."TT#PB_DATA_JP" MODIFY ("C#MN" NOT NULL ENABLE);
  ALTER TABLE "FCR"."TT#PB_DATA_JP" MODIFY ("C#TAR_VAL" NOT NULL ENABLE);
  ALTER TABLE "FCR"."TT#PB_DATA_JP" MODIFY ("C#C_SUM" NOT NULL ENABLE);
  ALTER TABLE "FCR"."TT#PB_DATA_JP" MODIFY ("C#M_SUM" NOT NULL ENABLE);
  ALTER TABLE "FCR"."TT#PB_DATA_JP" MODIFY ("C#P_SUM" NOT NULL ENABLE);
  ALTER TABLE "FCR"."TT#PB_DATA_JP" MODIFY ("C#FC_SUM" NOT NULL ENABLE);
  ALTER TABLE "FCR"."TT#PB_DATA_JP" MODIFY ("C#FP_SUM" NOT NULL ENABLE);
