--------------------------------------------------------
--  DDL for Table TT#REPORTS_J
--------------------------------------------------------

  CREATE TABLE "FCR"."TT#REPORTS_J" 
   (	"C#ACCOUNT_ID" NUMBER(*,0), 
	"C#MN" NUMBER(4,0), 
	"C#TAR_VAL" NUMBER, 
	"C#C_SUM" NUMBER(38,2), 
	"C#M_SUM" NUMBER(38,2), 
	"C#P_SUM" NUMBER(38,2), 
	"C#FC_SUM" NUMBER(38,2), 
	"C#FP_SUM" NUMBER(38,2), 
	"C#NUM" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS#DATA1" ;
