--------------------------------------------------------
--  Constraints for Table TT#REPORTS_J
--------------------------------------------------------

  ALTER TABLE "FCR"."TT#REPORTS_J" MODIFY ("C#ACCOUNT_ID" NOT NULL ENABLE);
  ALTER TABLE "FCR"."TT#REPORTS_J" MODIFY ("C#MN" NOT NULL ENABLE);
  ALTER TABLE "FCR"."TT#REPORTS_J" MODIFY ("C#TAR_VAL" NOT NULL ENABLE);
  ALTER TABLE "FCR"."TT#REPORTS_J" MODIFY ("C#C_SUM" NOT NULL ENABLE);
  ALTER TABLE "FCR"."TT#REPORTS_J" MODIFY ("C#M_SUM" NOT NULL ENABLE);
  ALTER TABLE "FCR"."TT#REPORTS_J" MODIFY ("C#P_SUM" NOT NULL ENABLE);
  ALTER TABLE "FCR"."TT#REPORTS_J" MODIFY ("C#FC_SUM" NOT NULL ENABLE);
  ALTER TABLE "FCR"."TT#REPORTS_J" MODIFY ("C#FP_SUM" NOT NULL ENABLE);
