--------------------------------------------------------
--  DDL for Table TT#TOSK_ALL_PAY_09_2018
--------------------------------------------------------

  CREATE TABLE "FCR"."TT#TOSK_ALL_PAY_09_2018" 
   (	"NN" VARCHAR2(10 BYTE), 
	"PER" VARCHAR2(26 BYTE), 
	"ACC_NUM" VARCHAR2(20 BYTE), 
	"PUNKT" VARCHAR2(50 BYTE), 
	"PAY_SUM" NUMBER(10,2), 
	"PAY_NUM" VARCHAR2(50 BYTE), 
	"PAY_DATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS#DATA1" ;
