--------------------------------------------------------
--  DDL for Table TT#TEPLORES_ALL_LS
--------------------------------------------------------

  CREATE TABLE "FCR"."TT#TEPLORES_ALL_LS" 
   (	"FIO" VARCHAR2(100 BYTE), 
	"LS" VARCHAR2(20 BYTE), 
	"TOWN" VARCHAR2(26 BYTE), 
	"STREET" VARCHAR2(128 BYTE), 
	"HOUSE" VARCHAR2(50 BYTE), 
	"ROOM" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS#DATA1" ;
