--------------------------------------------------------
--  Constraints for Table TT#TOSK_ALL_LS_ADDR_LIKE
--------------------------------------------------------

  ALTER TABLE "FCR"."TT#TOSK_ALL_LS_ADDR_LIKE" MODIFY ("ACCOUNT_ID" NOT NULL ENABLE);
  ALTER TABLE "FCR"."TT#TOSK_ALL_LS_ADDR_LIKE" MODIFY ("ROOMS_ID" NOT NULL ENABLE);
  ALTER TABLE "FCR"."TT#TOSK_ALL_LS_ADDR_LIKE" MODIFY ("ACC_NUM" NOT NULL ENABLE);
  ALTER TABLE "FCR"."TT#TOSK_ALL_LS_ADDR_LIKE" MODIFY ("HOUSE_ID" NOT NULL ENABLE);
  ALTER TABLE "FCR"."TT#TOSK_ALL_LS_ADDR_LIKE" MODIFY ("HOUSE_NUM" NOT NULL ENABLE);
  ALTER TABLE "FCR"."TT#TOSK_ALL_LS_ADDR_LIKE" MODIFY ("FLAT_NUM" NOT NULL ENABLE);
