--------------------------------------------------------
--  DDL for Index TT#TOSK_ALL_PAY_09_2018_INDEX1
--------------------------------------------------------

  CREATE INDEX "FCR"."TT#TOSK_ALL_PAY_09_2018_INDEX1" ON "FCR"."TT#TOSK_ALL_PAY_09_2018" ("NN") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS#DATA1" ;
