--------------------------------------------------------
--  DDL for Table TT_V#CHOP
--------------------------------------------------------

  CREATE TABLE "FCR"."TT_V#CHOP" 
   (	"C#ACCOUNT_ID" NUMBER(*,0), 
	"C#WORK_ID" NUMBER(*,0), 
	"C#DOER_ID" NUMBER(*,0), 
	"C#MN" NUMBER, 
	"C#A_MN" NUMBER(4,0), 
	"C#B_MN" NUMBER(4,0), 
	"C#C_VOL" NUMBER, 
	"C#C_SUM" NUMBER, 
	"C#MC_SUM" NUMBER, 
	"C#M_SUM" NUMBER, 
	"C#MP_SUM" NUMBER, 
	"C#P_SUM" NUMBER, 
	"C#FC_SUM" NUMBER, 
	"C#FP_SUM" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS#DATA1" ;
