--------------------------------------------------------
--  DDL for View V3_CONTRACTS
--------------------------------------------------------

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "FCR"."V3_CONTRACTS" ("CONTRACT_ID", "CONTRACT_DATE", "CONTRACT_NUM", "CONTRACT_TYPE_ID", "CONTRACT_TYPE_NAME", "CONTRACT_DESCRIPTION", "CONTRACTOR_ID", "CONTRACTOR_NAME", "CONTRACTOR_INN", "CONTRACTOR_KPP", "CONTRACTOR_BANK_ACCOUNT", "CONTRACTOR_CONTACT_INFO", "CONTRACTOR_BANK_ID", "CONTRACTOR_1C_ID") AS 
  select
    T1.C#ID CONTRACT_ID,
    T1.C#DATE CONTRACT_DATE,
    T1.C#NUM CONTRACT_NUM,
    T1.C#CONTRACT_TYPE_ID CONTRACT_TYPE_ID,
    T3.C#NAME CONTRACT_TYPE_NAME,
    T1.C#DESCRIPTION CONTRACT_DESCRIPTION,
    T2.C#ID CONTRACTOR_ID,
    T2.C#NAME CONTRACTOR_NAME,
    T2.C#INN CONTRACTOR_INN,
    T2.C#KPP CONTRACTOR_KPP,
    T2.C#BANK_ACCOUNT CONTRACTOR_BANK_ACCOUNT,
    T2.C#CONTACT_INFO CONTRACTOR_CONTACT_INFO,
    T2.C#BANK_ID CONTRACTOR_BANK_ID,
    T2.C#1C_ID CONTRACTOR_1C_ID
from
  T3_CONTRACTS T1
  join T3_CONTRACTORS T2 on (T1.C#CONTRACTOR_ID = T2.C#ID)
  join T3_CONTRACT_TYPE T3 on (T1.C#CONTRACT_TYPE_ID = T3.c#ID)
;
