--------------------------------------------------------
--  DDL for View V3_JOBS
--------------------------------------------------------

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "FCR"."V3_JOBS" ("HOUSE_ID", "HOUSE_ADDR", "JOB_ID", "JOB_TYPE_ID", "JOB_TYPE_NAME", "REG_JOB_TYPE_ID", "REG_JOB_TYPE_NAME", "JOB_ELEM_CODE", "JOB_DATE_BEGIN", "JOB_DATE_END", "JOB_NOTE", "JOB_STATUS", "PLAN_SUM", "HOUSE_PLAN_SUM", "JOB_SUM", "HOUSE_SUM", "CONTRACT_ID", "CONTRACT_DATE", "CONTRACT_NUM", "CONTRACT_TYPE_NAME", "CONTRACT_DATE_BEGIN", "CONTRACT_DATE_END", "CONTRACT_SUM", "CONTRACT_DESCRIPTION", "CONTRACTOR_ID", "CONTRACTOR_NAME", "CONTRACTOR_INN", "CONTRACTOR_KPP", "CONTRACTOR_OGRN", "CONTRACTOR_CONTACT_INFO", "CONTRACTOR_1C_ID", "CONTRACTOR_BANK_BIC", "CONTRACTOR_BANK_KOR", "CONTRACTOR_BANK_NAME", "CONTRACTOR_BANK_ACCOUNT") AS 
  select
    C#HOUSE_ID HOUSE_ID, 
    P#UTILS.GET#HOUSE_ADDR(C#HOUSE_ID) HOUSE_ADDR, 
    T3_JOBS.C#ID JOB_ID, 
    JOB_TYPE.C#ID JOB_TYPE_ID, 
    JOB_TYPE.C#NAME JOB_TYPE_NAME, 
    REG_JOB_TYPE.C#ID REG_JOB_TYPE_ID, 
    REG_JOB_TYPE.C#NAME REG_JOB_TYPE_NAME, 
    JOB_TYPE.C#ELEM_CODE JOB_ELEM_CODE,
    T3_JOBS.C#DATE_BEGIN JOB_DATE_BEGIN, 
    T3_JOBS.C#DATE_END JOB_DATE_END, 
    T3_JOBS.C#NOTE JOB_NOTE, 
    C#STATUS JOB_STATUS,

    null PLAN_SUM,
    P3UTILS.GET_HOUSE_PLAN_SUMMA(C#HOUSE_ID) HOUSE_PLAN_SUM,
    P3UTILS.GET_JOB_SUMMA(T3_JOBS.C#ID) JOB_SUM,
    P3UTILS.GET_HOUSE_SUMMA(C#HOUSE_ID) HOUSE_SUM,

    C#CONTRACT_ID CONTRACT_ID, 
    C#DATE CONTRACT_DATE, 
    C#NUM CONTRACT_NUM, 
    T3_CONTRACT_TYPE.C#NAME CONTRACT_TYPE_NAME, 
    T3_CONTRACTS.C#DATE_BEGIN CONTRACT_DATE_BEGIN,
    T3_CONTRACTS.C#DATE_END CONTRACT_DATE_END,
    T3_CONTRACTS.C#SUM CONTRACT_SUM,
    C#DESCRIPTION CONTRACT_DESCRIPTION,

    T3_CONTRACTS.C#CONTRACTOR_ID CONTRACTOR_ID,
    T3_CONTRACTORS.C#NAME CONTRACTOR_NAME, 
    T3_CONTRACTORS.C#INN CONTRACTOR_INN, 
    T3_CONTRACTORS.C#KPP CONTRACTOR_KPP, 
    T3_CONTRACTORS.C#OGRN CONTRACTOR_OGRN, 
    T3_CONTRACTORS.C#CONTACT_INFO CONTRACTOR_CONTACT_INFO, 
    T3_CONTRACTORS.C#1C_ID CONTRACTOR_1C_ID,

    T3_BANK.C#BIC_NUM CONTRACTOR_BANK_BIC, 
    T3_BANK.C#CA_NUM CONTRACTOR_BANK_KOR, 
    T3_BANK.C#NAME CONTRACTOR_BANK_NAME, 
    C#BANK_ACCOUNT CONTRACTOR_BANK_ACCOUNT
from
    T3_JOBS
    LEFT JOIN T3_JOB_TYPE JOB_TYPE ON (T3_JOBS.C#JOB_TYPE_ID = JOB_TYPE.C#ID)
    LEFT JOIN T3_REG_JOB_TYPE REG_JOB_TYPE ON (JOB_TYPE.C#REG_JOB_TYPE_ID = REG_JOB_TYPE.C#ID)
    LEFT JOIN T3_CONTRACTS ON (T3_JOBS.C#CONTRACT_ID = T3_CONTRACTS.C#ID)
    LEFT JOIN T3_CONTRACT_TYPE ON (T3_CONTRACTS.C#CONTRACT_TYPE_ID = T3_CONTRACT_TYPE.C#ID)
    LEFT JOIN T3_CONTRACTORS ON (T3_CONTRACTS.C#CONTRACTOR_ID = T3_CONTRACTORS.C#ID)
    LEFT JOIN T3_BANK ON (T3_CONTRACTORS.C#BANK_ID = T3_BANK.C#ID)
;
