--------------------------------------------------------
--  DDL for View V#ACCOUNT_SPEC_VD
--------------------------------------------------------

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "FCR"."V#ACCOUNT_SPEC_VD" ("C#ID", "C#VN", "C#VALID_TAG", "C#SIGN_DATE", "C#SIGN_S_ID", "C#PERSON_ID", "C#PART_COEF", "C#ACCOUNT_ID", "C#SPEC_DATE") AS 
  SELECT 
  T#ACCOUNT_SPEC_VD."C#ID",T#ACCOUNT_SPEC_VD."C#VN",T#ACCOUNT_SPEC_VD."C#VALID_TAG",T#ACCOUNT_SPEC_VD."C#SIGN_DATE",T#ACCOUNT_SPEC_VD."C#SIGN_S_ID",T#ACCOUNT_SPEC_VD."C#PERSON_ID",T#ACCOUNT_SPEC_VD."C#PART_COEF"
  ,C#ACCOUNT_ID
  ,C#DATE C#SPEC_DATE
FROM
  T#ACCOUNT_SPEC,
  T#ACCOUNT_SPEC_VD 
where
  T#ACCOUNT_SPEC.C#ID = T#ACCOUNT_SPEC_VD.C#ID
;
