--------------------------------------------------------
--  DDL for View V#ACCOUNT_VD
--------------------------------------------------------

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "FCR"."V#ACCOUNT_VD" ("C#SPEC_ID", "C#SPEC_VN", "C#SPEC_SIGN_DATE", "C#SPEC_SIGN_S_ID", "C#PERSON_ID", "C#PART_COEF", "C#ACCOUNT_ID", "C#SPEC_DATE", "C#AVD_ID", "C#AVD_VN", "C#AVD_SIGN_DATE", "C#AVD_SIGN_S_ID", "C#END_DATE") AS 
  SELECT 
  V#ACCOUNT_SPEC_VD.C#ID C#SPEC_ID      
  ,V#ACCOUNT_SPEC_VD.C#VN C#SPEC_VN 
  ,V#ACCOUNT_SPEC_VD.C#SIGN_DATE C#SPEC_SIGN_DATE
  ,V#ACCOUNT_SPEC_VD.C#SIGN_S_ID C#SPEC_SIGN_S_ID
  ,V#ACCOUNT_SPEC_VD.C#PERSON_ID C#PERSON_ID                            
  ,V#ACCOUNT_SPEC_VD.C#PART_COEF C#PART_COEF                           
  ,V#ACCOUNT_SPEC_VD.C#ACCOUNT_ID C#ACCOUNT_ID
  ,V#ACCOUNT_SPEC_VD.C#SPEC_DATE C#SPEC_DATE      
  ,T#ACCOUNT_VD.C#ID C#AVD_ID      
  ,T#ACCOUNT_VD.C#VN C#AVD_VN 
  ,T#ACCOUNT_VD.C#SIGN_DATE C#AVD_SIGN_DATE                            
  ,T#ACCOUNT_VD.C#SIGN_S_ID C#AVD_SIGN_S_ID
  ,T#ACCOUNT_VD.C#END_DATE C#END_DATE
FROM
  V#ACCOUNT_SPEC_VD
    LEFT OUTER JOIN T#ACCOUNT_VD
       ON V#ACCOUNT_SPEC_VD.C#SIGN_DATE = T#ACCOUNT_VD.C#SIGN_DATE
       AND  V#ACCOUNT_SPEC_VD.C#ACCOUNT_ID = T#ACCOUNT_VD.C#ID
;
