--------------------------------------------------------
--  DDL for Index X#PS#ACC_ID2
--------------------------------------------------------

  CREATE INDEX "FCR"."X#PS#ACC_ID2" ON "FCR"."T#PAY_SOURCE" (COALESCE("C#ACC_ID","C#ACC_ID_CLOSE","C#ACC_ID_TTER")) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS#DATA1" ;
